### PR TITLE
RHPAM-2554 - Require the ability to define mandatory process /case va…

### PR DESCRIPTION
**Pull request by mswiderski**
…riables that can only be changed by Admin

depends on
https://github.com/kiegroup/droolsjbpm-knowledge/pull/422
https://github.com/kiegroup/drools/pull/2756 

@gmunozfe @elguardian could you please review?

Overall idea is to register additional event listener that can react on beforeVariableChange event to enforce any security restrictions based on custom tags associated with variables.

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by gmunozfe** [comment]
@mswiderski there are 3 compilations failures.

At `AddDataCaseFileInstanceCommand`, `ReopenCaseCommand` when invoking `fireAfterVariableChanged`, it's missing the new param (List<String>):

Not sure if there's another easier way to retrieve it:
`VariableScope variableScope = ((VariableScope) ((RegistryContext) context).get(VariableScope.VARIABLE_SCOPE));`

And then, inside the fireAfterVariableChanged call:

`variableScope == null ? null : variableScope.tags(name)`

Last failure is at CachedProcessVariableChangedEvent (jbpm-test-coverage) that missing unimplemented methods:

       @Override
        public List<String> getTags() {
            return Collections.emptyList();
        }

        @Override
        public boolean hasTag(String tag) {
            return false;
        }


If you agree, I can create a PR to your branch.

**Comment by mswiderski** [comment]
@gmunozfe thanks a lot, and go ahead with PR :)

**Comment by elguardian** [comment]
@mswiderski  looks good to me.

**Comment by gmunozfe** [comment]
@mswiderski I've created several tests for case scenarios:

- The way I proposed for retrieving `VariableScope` from Context was not working, the new proposal does.

- For the commands `addDataToCaseFile` and `reopenCase`, only the `fireAfterVariableChanged` was invoked, so there is no validation in these scenarios. I guess `fireBeforeVariableChanged` should also be called, and then these new tests are passing.

I am creating a PR to your branch for you to review if this proposal is valid or not.

**Comment by elguardian** [comment]
Jenkins retest this please

**Comment by elguardian** [comment]
@gmunozfe any progress ?

**Comment by gmunozfe** [comment]
> @gmunozfe any progress ?

sorry, I was trying to test a case with the 3 constraints: required, readonly and restricted.

However, readonly is not validated, because `oldValue` has been already set:

https://github.com/kiegroup/jbpm/blob/b3a1d1ccd7fe513b4d3a1f8b8708285308e12ac3/jbpm-flow/src/main/java/org/jbpm/process/instance/context/variable/VariableScopeInstance.java#L108

Checking why that value is not null, as expected...
^ @mswiderski

**Comment by gmunozfe** [comment]
https://github.com/kiegroup/jbpm/blob/b3a1d1ccd7fe513b4d3a1f8b8708285308e12ac3/jbpm-flow/src/main/java/org/jbpm/process/instance/context/variable/VariableScopeInstance.java#L83

caseFile already has that variable with its value, therefore the setVariable is considering the operation as a modification, violating readonly policy.

**Comment by mswiderski** [comment]
@gmunozfe I would say that this is expected behaviour, since case file variable can be fetched as process variable and since it was marked as readonly it should cause the exception. Or am I misunderstanding something here...

**Comment by gmunozfe** [comment]
OK, thanks @mswiderski I was thinking that "readonly" meant "only can be assigned once"

**Comment by elguardian** [comment]
@gmunozfe @mswiderski is this ready to merge ?

**Comment by mswiderski** [comment]
@elguardian yes, from my point of view

**Comment by gmunozfe** [comment]
@elguardian sure, this is ok to merge

**Pull request merged**
