### PR TITLE
[7.67.x][JBPM-10080] DDLScripts errors after JBPM-10072

### PR DESCRIPTION
**Pull request by gmunozfe**
**JIRA**: [JBPM-10080](https://issues.redhat.com/browse/JBPM-10080)

backported from 09c723307974d42b3a242e6563ae07099396d046

### CODE REVIEW

**Review by afalhambra — APPROVED** [review]
well done!

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
@mareknovotny this is ready to merge into 7.67.x

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
do we have a product jira?

**Comment by gmunozfe** [comment]
> do we have a product jira?

no, the scripts with the issue have not been released yet (they are at 7.13 CR1)

**Comment by mareknovotny** [comment]
yes, that is the problem this branch 7.67.x is opened only for blockers/critical problems on CR1

**Comment by afalhambra** [comment]
> yes, that is the problem this branch 7.67.x is opened only for blockers/critical problems on CR1

@mareknovotny, please find below the link to the jira blocker for 7.13 related to this PR
https://issues.redhat.com/browse/RHPAM-4373

**Comment by gmunozfe** [comment]
@mareknovotny this can be merged

**Comment by mareknovotny** [comment]
could you please backport this change also to 7.67.x-blue branch, thanks in advance

**Pull request merged**
