### PR TITLE
Upgrade shrinkwrap in jbpm-container

### PR DESCRIPTION
**Pull request by MarianMacik**
…ly Aether)

@mareknovotny 

Depends on kiegroup/droolsjbpm-build-bootstrap/pull/680

Marian

### CODE REVIEW

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by MarianMacik** [comment]
This does not further depend on kiegroup/droolsjbpm-build-bootstrap#680.

**Comment by MarianMacik** [comment]
Jenkins retest this

**Comment by MarianMacik** [comment]
Jenkins execute full downstream build

**Pull request merged**
