### PR TITLE
[7.67.x-blue]..[JBPM-10094]- Current index settings might cause DeadLocks in SQL Server

### PR DESCRIPTION
**Pull request by VaniHaripriya**
JIRA: https://issues.redhat.com/browse/JBPM-10094

Updated the index settings in all the Dbs to resolve the DeadLocks under stress tests.

### CODE REVIEW

**Review by gmunozfe — APPROVED** [review]
Test failures unrelated. Good job @VaniHaripriya !

**Comment by elguardian** [comment]
@VaniHaripriya plz fix so I can merge

**Comment by VaniHaripriya** [comment]
> @VaniHaripriya plz fix so I can merge

@elguardian  Conflicts have been fixed. Please merge.

**Comment by VaniHaripriya** [comment]
Jenkins retest this please

**Pull request merged**
