### PR TITLE
[Do not MERGE yet] RHDM-251 Wildfly 11 upgrade

### PR DESCRIPTION
**Pull request by mareknovotny**

### CODE REVIEW

**Comment by MarianMacik** [comment]
Sure, was going to :) Everything looks ok, just please update the README accordingly: https://github.com/kiegroup/jbpm/blob/master/jbpm-container-test/jbpm-in-container-test/README.md. And bear in mind that the PR builder won't run this since there is -Dcontainer.profile=wildfly10 configured I believe. We need to run this with wildfly11. @mareknovotny Can we run it on our Jenkins somehow?

**Comment by mareknovotny** [comment]
@MarianMacik this is a little controversial as changing wildfly10 to wildfly11 will invalidate some PRs not ready, but I ran it locally before if you believe me. That's why I haven't merged it yet as I waited for some pause in release and fixing bugs to not affect somebody in PR queue.
I will update readme quickly

**Comment by MarianMacik** [comment]
@mareknovotny Sure I believe you. Then I am quite surprised it works, especially remote EJB tests.

**Comment by mareknovotny** [comment]
So @krisv was talking about to merge whole set of PRs after releasing the 7.6.0.Final which should be now in progress I think.

**Pull request merged**
