### PR TITLE
[6.5.x] JBPM-5369 RHBPMS-4369 Could not parse knowledge when creating Runtime…

### PR DESCRIPTION
**Pull request by mariofusco**
…Manager concurrently (#637)

* JBPM-5369 - fix for RuleFlowProcessValidator concurrency issue - removed duplicite validation of start and end nodes.

* JBPM-5369 - Removed unused imports.

(cherry picked from commit eef6b0c900105e0bed134307e7853a9f7de8614c)

### CODE REVIEW

**Comment by mariofusco** [comment]
@mswiderski This PR fixes on branch 6.5.x the concurrency problem reported by customer. I don't think it should be merged till we don't have acks for this, but I sent it to allow William to give it a try.

**Comment by mswiderski** [comment]
thanks @mariofusco 

is this a back port as I recall you mentioned it was not reproducible on master not 7.0.x?

**Comment by mariofusco** [comment]
@mswiderski Yes, this is the cherry-pick of this https://github.com/kiegroup/jbpm/commit/eef6b0c900105e0bed134307e7853a9f7de8614c

**Comment by mariofusco** [comment]
ok to test

**Pull request merged**
