### PR TITLE
JBPM-5610: Not able to exclude multiple owners for HumanTask - Tests

### PR DESCRIPTION
**Pull request by domhanak**
**Add tests with groups and excluded owners**

Adds 2 tests methods that test behavior of excluding user/users
from group which is set as potential owner of the task.

### CODE REVIEW

**Comment by livthomas** [comment]
I do not think it is a good idea to reference our internal JIRA in the commit message.

**Comment by mswiderski** [comment]
fully agree with @livthomas

**Comment by domhanak** [comment]
@livthomas @mswiderski Yes, I am sorry for that, reworded the commit message.

**Comment by domhanak** [comment]
Should I change the PRQ name too?

**Comment by mswiderski** [comment]
thanks @domhanak

**Pull request merged**
