### PR TITLE
[JBPM-9819] - SLATrackingCommandTest#testSLATrackingOnUserTaskSLAMet test is failing on master

### PR DESCRIPTION
**Pull request by afalhambra**
**[JBPM-9819](https://issues.redhat.com/browse/JBPM-9819)**: SLATrackingCommandTest#testSLATrackingOnUserTaskSLAMet test is failing on master

### CODE REVIEW

**Review by fjtirado — APPROVED** [review]
Great work @afalhambra 
Just wondering if collect can be replaced by findFirst

**Comment by afalhambra** [comment]
> Great work @afalhambra
> Just wondering if collect can be replaced by findFirst

Yes, changed to findAny. Thanks!

**Comment by afalhambra** [comment]
Jenkins retest this

**Comment by afalhambra** [comment]
Jenkins retest this

**Comment by afalhambra** [comment]
@mareknovotny could you please merge?

**Pull request merged**
