### PR TITLE
[BXMSPROD-1367] - [Improve community CI] [jbpm] timeout

### PR DESCRIPTION
**Pull request by afalhambra**
**[BXMSPROD-1367](https://issues.redhat.com/browse/BXMSPROD-1367)**: [Improve community CI] [jbpm] timeout

### CODE REVIEW

**Comment by afalhambra** [comment]
Unable to reproduce the issue - though the test may hang due to a deprecated in-memory server. Just replaced it for a more updated version of the same in the PR.

**Review by gmunozfe — APPROVED** [review]
Looks good to me, let's see if it's enough, well done @afalhambra !

**Comment by afalhambra** [comment]
Jenkins retest this

**Comment by afalhambra** [comment]
@mareknovotny could you please merge? thanks!

**Comment by afalhambra** [comment]
@mareknovotny just a reminder, if you can please merge this. Thanks again

**Pull request merged**
