### PR TITLE
JBPM-8404

### PR DESCRIPTION
**Pull request by DuncanDoyle**
Introduced new DocumentCollection and DocumentCollectionImpl to split interface and impl defitinition of a collection of documents. Deprecated the old Documents impl as that gave problems when marshalling and unmarshalling via JSON and JAXB due to the Collection of interfaces it contained.

### CODE REVIEW

**Comment by MarianMacik** [comment]
Maybe full downstream would be beneficial here? Just to test this with KIE Server...

jenkins execute full downstream build

**Comment by pefernan** [comment]
@mswiderski @DuncanDoyle this affects my PRs but if we want to have this change in for me +1 to merge it asap so I have time to solve the forms part and jbpm-wb part

**Comment by mswiderski** [comment]
@pefernan so you're ok to merge this before https://github.com/kiegroup/jbpm/pull/1480 as these two are in conflict I believe. So one or the other needs to be modified afterwards

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by MarianMacik** [comment]
FDB looks ok. No document/marshalling related issues.

**Comment by mswiderski** [comment]
looks like the regular build timed out so let's wait for it again

**Comment by pefernan** [comment]
@mswiderski @MarianMacik downstream is failing due to some unrelated tests. Let's trigger it again to have it running but for me +1 to merge.

**Comment by pefernan** [comment]
jenkins execute full downstream build please

**Pull request merged**
