### PR TITLE
[RHPAM-2] NullPointerException during transaction rollback when using CMT

### PR DESCRIPTION
**Pull request by elguardian**
integration test for RHPAM-2

https://github.com/kiegroup/drools/pull/2015

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by elguardian** [comment]
NOTE: @mswiderski  this test will fail as the other pr is not merged

**Comment by mswiderski** [comment]
can you name the branch the same as the other one so it will then pick it up

**Comment by elguardian** [comment]
superseeded by https://github.com/kiegroup/jbpm/pull/1315

**Pull request closed without merging**
