### PR TITLE
JBPM-10112: Expand class name of fundamental java classes if not defi…

### PR DESCRIPTION
**Pull request by martinweiler**
…ned as FQCN to address org.xmlpull.v1.XmlPullParserException in VariableScope.validateVariable

**Thank you for submitting this pull request**

**JIRA**: [JBPM-10112](https://issues.redhat.com/browse/JBPM-10112)

Due to the changes from JBPM-9924, a variable defined as "Object" (without package name), holding a String value fails to be validated. The proposed fix improves the class resolution in ObjectDataType.verifyDataType by adding the 'java.lang.' package to the className in an additional check.

### CODE REVIEW

**Review by elguardian — APPROVED** [review]
LGTM

**Comment by elguardian** [comment]
Jenkins retest this please

**Comment by martinweiler** [comment]
@elguardian please review the updated fix which has been extended to handle validation of Date variables.

**Comment by elguardian** [comment]
@martinweiler failing one test. seems related.

**Comment by martinweiler** [comment]
@elguardian thanks, this should be addressed now

**Comment by martinweiler** [comment]
Jenkins retest this please

**Pull request merged**
