### PR TITLE
[6.5.x] RHBPMS-5173 - Signal on boundary event causes an unwanted event listener message

### PR DESCRIPTION
**Pull request by elguardian**
the cancel method should avoid firing and after node
left event causing an unwanted log.

cherry picked from #1226

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
Jenkins retest this

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
same here @mareknovotny shall this be merged? does it target any patch release?

**Comment by mareknovotny** [comment]
We haven't agreed on inclusion in JIRA, so this is now obsolete I think until someone stand up with the request to merge still. I will keep that decision on you @mswiderski, please follow up on JIRA.

**Comment by mswiderski** [comment]
@mareknovotny I am closing this PR as there is no response in jira on what to do with it, it can always be reopen so @elguardian please don't delete your branch

**Pull request closed without merging**
