### PR TITLE
[JBPM-9902] RestServiceInvokeTest failing for Tomcat after migrating to jakarta

### PR DESCRIPTION
**Pull request by gmunozfe**
**JIRA**: [JBPM-9902](https://issues.redhat.com/browse/JBPM-9902)

### CODE REVIEW

**Comment by gmunozfe** [comment]
jenkins execute tomcat build

**Review by afalhambra — APPROVED** [review]
Looks good to me! nice one @gmunozfe

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
Fixed by https://github.com/kiegroup/jbpm/pull/2035

**Pull request closed without merging**
