### PR TITLE
JBPM-5880 - 'async' as a default option for all tasks - test stabiliz…

### PR DESCRIPTION
**Pull request by mswiderski**
…ation

@tsurdilo here is an attempt to make these tests more stable (or completely stable) ... as they cause false alarms on PR builds

### CODE REVIEW

**Comment by tsurdilo** [comment]
@mswiderski very nice!!!

**Comment by MarianMacik** [comment]
Interesting, what was the problem with Process Event Listener?

**Comment by mswiderski** [comment]
@MarianMacik  the problem is that process engine and its transaction will complete earlier than the job that triggered to reach the end - as they are two separate transactions. So it could be that the latch is released before executor saved the status of the last command making it fail on assert.

Again, this is just an attempt so we'll see if it will help...

**Comment by mswiderski** [comment]
ok, still failing ... will take another look

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by MarianMacik** [comment]
So I checked the output a little bit and the last AsyncSignalEventCommand with id=3 is still in status RUNNING. And after that you can see that there is:
``` 
ERROR The object is already closed [90007-173]
ERROR HHH000337: Unable to mark for rollback on PersistenceException: 
org.hibernate.service.UnknownServiceException: Unknown service requested
```

but maybe it is because the executor is destroyed while the command is still running. I am only guessing though. So should the test wait a little bit more to make sure that all jobs are in DB?

**Comment by mswiderski** [comment]
@MarianMacik exactly, that was the purpose of the refined commit to collect more information. This now proves it is the issue with command not being yet completed before we assert on it.

One option would be to query first for running jobs and wait a bit if there are found otherwise go straight to asserts. Wdyt?

**Comment by MarianMacik** [comment]
Yes, that would be quite clean. We can include even a loop which will e.g. wait 100 ms, but max 10 iterations and every time it will check if there are any jobs which are still running - I think it is better then permanent Thread sleep for 1 sec. So I agree with your solution.

With regards to my last section in previous comment - why is this even happening? I would have thought that Executor thread will complete process by executing async signal which will invoke Process listener which will register afterCompletion countDown(), so after Executor job is finished and committed, everything should be in DB and the test can continue.

**Comment by mswiderski** [comment]
@MarianMacik correct, that was what I expected as well. Though keep in mind that executor will commit tx for process and then do some work on the job itself - like call other callbacks (if any) and then update the job and commit to db. Somehow this last step is not done or done too late... using the async job listeners should prevent it but it then led to timeout of the test which would indicate the job does not complete somehow...

**Comment by MarianMacik** [comment]
@mswiderski so you are saying that there is another possibility to use AsyncJobListener (as you did with logging) but then it timed out, that shouldn't be happenning right? That is even stranger. But we will see after a little wait if the last job gets finished, I hope it will. Thanks for clarification ;)

**Comment by mswiderski** [comment]
@MarianMacik @tsurdilo first build is green with the wait for all jobs to finish check. let's see few more times...

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
ok, 4 builds in a roll without failures with AsyncMode tests, so I think we are good

**Comment by mswiderski** [comment]
removed the debug listener so we'll have another build

**Comment by mswiderski** [comment]
Ok 5 builds in a roll with all green, I think it's ready to be merged

**Pull request merged**
