### PR TITLE
JBPM-6842 - Redesign jBPM executor to replace polling mechanism with …

### PR DESCRIPTION
**Pull request by mswiderski**
…more efficient approach

depends on https://github.com/kiegroup/droolsjbpm-knowledge/pull/293

it's not finished yet, still work in progress... just checking if jenkins is happy with changes while still performing additional tests locally

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
@mswiderski Just out of curiosity, have you considered using java time API from Java 8 for date and time related operations?

**Comment by mswiderski** [comment]
@sutaakar yes, I did though didn't find much justification to add them. There are not many nor complex operations on date/time. Or did you find anything that would benefit from using java 8 time api?

**Comment by sutaakar** [comment]
@mswiderski ok, no specific reason for that, I was just curious.

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
alright, 5 builds in a roll completed successfully so I believe this is good for merge. Additional, build takes around 5 min less which is good too :)

**Pull request merged**
