### PR TITLE
[7.7.x] RHPAM-275: A user can display tasks for which he is not Potential Owner or Bussines Admin

### PR DESCRIPTION
**Pull request by pefernan**
Copy of https://github.com/kiegroup/jbpm/pull/1201

@mswiderski Could you please review?

This is part of an ensemble merge with:
https://github.com/kiegroup/jbpm/pull/1202
https://github.com/kiegroup/droolsjbpm-integration/pull/1445
https://github.com/kiegroup/jbpm-wb/pull/1075

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by pefernan** [comment]
jenkins retest this please

**Comment by pefernan** [comment]
jenkins retest this please

**Pull request merged**
