### PR TITLE
[JBPM-9684] Add task description

### PR DESCRIPTION
**Pull request by ruromero**
Signed-off-by: ruromero <rromerom@redhat.com>

**Thank you for submitting this pull request**

**JIRA**: 

[https://issues.redhat.com/browse/JBPM-9684](https://issues.redhat.com/browse/JBPM-9684)

Add task description to `GetTasksByIdList` query and `UserTaskInstanceWithPotOwnerDesc` POJO

### CODE REVIEW

**Comment by ruromero** [comment]
@elguardian do you know what failed in the ci-build?

**Review by afalhambra — CHANGES_REQUESTED** [review]
Just one change requested as per my review.
I think we should also add/modify one of the current tests to make sure we're fetching the task description properly.

**Comment by ruromero** [comment]
@afalhambra done, thanks!

**Comment by ruromero** [comment]
jenkins retest this

**Review by afalhambra — APPROVED** [review]
Great job

**Comment by yesamer** [comment]
@ruromero @afalhambra @elguardian Hi Guys! I afraid the changes introduced in this PR affects integrations tests defined in `droolsjbpm-integration` repo, in particular here: https://github.com/yesamer/droolsjbpm-integration/blob/master/kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/QueryDataServiceBaseTest.java#L59

For that reason we are not able to build that repo (eg. https://github.com/kiegroup/droolsjbpm-integration/pull/2448)
`10:23:18  [ERROR] /home/jenkins/workspace/KIE/master/pullrequest/droolsjbpm-integration-master.pr/bc/kiegroup_droolsjbpm_integration/kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/QueryDataServiceBaseTest.java:[59,53] no suitable constructor found for UserTaskInstanceWithPotOwnerDesc(java.lang.String,java.lang.String,java.util.Date,java.util.Date,java.lang.Long,java.lang.String,int,java.lang.Long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
10:23:18  [ERROR]     constructor org.jbpm.kie.services.impl.model.UserTaskInstanceWithPotOwnerDesc.UserTaskInstanceWithPotOwnerDesc(java.lang.Long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.util.Date,java.lang.String,java.util.Date,java.util.Date,java.lang.String,java.lang.Integer,java.lang.String,java.lang.Long,java.lang.String,java.lang.String,java.lang.String) is not applicable
10:23:18  [ERROR]       (actual and formal argument lists differ in length)`

Can you please update the tests accordingly to your changes? Thanks!

**Comment by mareknovotny** [comment]
I was just writing the same comment as @yesamer 
please fix it ASAP!

**Comment by elguardian** [comment]
@mareknovotny https://github.com/kiegroup/jbpm/pull/1912 reverting

**Comment by ruromero** [comment]
@mareknovotny @yesamer the changes for the droolsjbpm-integration are included in this PR https://github.com/kiegroup/droolsjbpm-integration/pull/2440
I have fixed the constructor in the other PR and once it is merged, the build should succeed.

**Comment by yesamer** [comment]
Thank you @ruromero

**Pull request merged**
