### PR TITLE
[6.5.x] RHBPMS-5164: IllegalArgumentException: Unknown node id" when migrating MultiInstance

### PR DESCRIPTION
**Pull request by mareknovotny**
https://issues.jboss.org/browse/RHBPMS-5164

### CODE REVIEW

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
Here the failed tests are probably not random issues, I can reproduce locally one of the failure
```
MigrationManagerTest.testMigrateUserTaskProcessInstanceDifferentRuntimeManagers:568 expected:<UserTask-[1]> but was:<UserTask-[2]>
```

**Comment by mareknovotny** [comment]
Jenkins retest this

**Pull request merged**
