### PR TITLE
JBPM-9227: cargo container upgrade to wildfly19x

### PR DESCRIPTION
**Pull request by mareknovotny**
https://issues.redhat.com/browse/JBPM-9227

Parent PR kiegroup/droolsjbpm-build-bootstrap#1390

### CODE REVIEW

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
All 16 failures are with the same error

```
DeploymentScenario contains a target (remote-container) not matching any defined Container in the registry.
Possible causes are: None of the 1 Containers are marked as default or you have defined a @Deployment with a @TargetsContainer of value (remote-container) that does not match any found/configured Containers (default), see arquillian.xml container@qualifier
```
Is it possible to be related to missing `-Dcontainer=wildfly` in the mvn command? @MarianMacik ?

**Comment by mareknovotny** [comment]
Jenkins retest this please

now trying with that missing property

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Pull request merged**
