### PR TITLE
JBPM-6487 Jbpm tests stabilisation

### PR DESCRIPTION
**Pull request by dcihak**
Fixes CommandBasedAuditLogServiceTest and several asserts in testAsyncAuditLoggerCompleteWithVariablesCustomIndexer related to variable values and IDs loaded from audit log.

### CODE REVIEW

**Comment by MarianMacik** [comment]
@dcihak If you are still working on this PR, please put [DO NOT MERGE] in its title so we know we don't have to approve it yet. ;)

**Comment by mswiderski** [comment]
is this ready to be merged?

**Comment by MarianMacik** [comment]
@dcihak is on PTO, but should be back tomorrow I guess. I consider it as under development.

**Comment by tsurdilo** [comment]
@dcihak is there a jira available for this by chance?

**Comment by MarianMacik** [comment]
@tsurdilo I think there isn't any. But will double check tomorrow and we will create one for @dcihak if there is none.

**Comment by dcihak** [comment]
READY

**Pull request merged**
