### PR TITLE
[7.59.x][JBPM-9897] Stabilize bpmn2 tests with cron in boundary timers

### PR DESCRIPTION
**Pull request by gmunozfe**
**JIRA**: [JBPM-9897](https://issues.redhat.com/browse/JBPM-9897)

cherry-picked from 92131f4223a7bf429a7492685b5973fa1de80d34

### CODE REVIEW

**Review by afalhambra — APPROVED** [review]
LGTM

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
@mareknovotny done (though I'm not sure if it's late to merge)

**Comment by mareknovotny** [comment]
> @mareknovotny done (though I'm not sure if it's late to merge)

no, at all, any stabilization are welcomed anytime.

**Pull request merged**
