### PR TITLE
[6.5.x] [RHBPMS-5247] Control which classes are registered for serialization at kjar level

### PR DESCRIPTION
**Pull request by elguardian**
port http://git.app.eng.bos.redhat.com/git/kiegroup/jbpm.git/commit/?h=RHBPMS-5237&id=869f89a0c8666e89d817c4880d300c992de463aa

### CODE REVIEW

**Comment by MarianMacik** [comment]
BTW this change is not backward-compatible. Do we really want this in 6.5.x stream? I have just noticed that in DeploymentDescriptor the default is `false`:

https://github.com/kiegroup/jbpm/blob/2b9fe30ace384ed81bbc30242c7d3cc64794e351/jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/deploy/DeploymentDescriptorImpl.java#L111

So we probably will need to alter the default there as well, not mentioning the JavaDoc:

https://github.com/kiegroup/droolsjbpm-knowledge/blob/a8ea70a510a44d9a50189cfbbab0d275be75fe47/kie-internal/src/main/java/org/kie/internal/runtime/conf/DeploymentDescriptor.java#L154-L162

@mswiderski isn't it the case that all deployment units have at least default deployment descriptor?

**Comment by elguardian** [comment]
I will see the failing tests today
@MarianMacik this is already in a one-off in 6.4.z (6.5.x branch).
In theory in SET procedure a one-off should have a jira provided in the sustaining stream it was merged and become blocker for the next CP (no regressions policy). So if there is one-off approved that means it should be automatically devel-ack by SET and provided a forward port. otherwise that one-off should not exists.
@mareknovotny thoughts ?

**Comment by mareknovotny** [comment]
@martinweiler please check previous comment from https://github.com/kiegroup/jbpm/pull/1487#issuecomment-487638665 as it seems this shoulld not be included in micro due backward compatible change.

**Comment by martinweiler** [comment]
@MarianMacik - true, this fix changes the behavior from 6.4.11. This was discussed [here](http://post-office.corp.redhat.com/archives/jboss-support-droolsjbpm/2018-August/msg00131.html) and @mswiderski suggested this code change.

@elguardian true that we should have a JIRA for the branch first before we create a one-off, but this was not done here as the plan had been not to release any CPs after 6.4.11.

**Comment by MarianMacik** [comment]
I'm OK with that, then we should just emphasize this change in behaviour in the release notes so users are not surprised with the change.

**Comment by elguardian** [comment]
Jenkins retest this please.

**Comment by mareknovotny** [comment]
We need a decision if we can merge it due the change of the behavior or NOT.

**Comment by krisv** [comment]
@mswiderski can you confirm and if so merge?

**Comment by MarianMacik** [comment]
also what about the https://github.com/kiegroup/jbpm/pull/1487#issuecomment-487638665 - shouldn't we alter JavaDoc and default value for DeploymentDescriptor class as well?

**Comment by mswiderski** [comment]
from my point of view this is not really breaking any compatibility as it is more to guard the deployment itself from attempting to deploy classes that won't really work for remote invocation. So +1 from to go ahead and merge.

**Comment by mareknovotny** [comment]
Jenkins retest this please.

**Pull request merged**
