### PR TITLE
[6.5.x] RHBPMS-5203 - Timers in composite nodes are not migrated

### PR DESCRIPTION
**Pull request by mswiderski**

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
is this timeout random or just an issue with test environment?
```
Error Message

test timed out after 10000 milliseconds

Stacktrace

org.junit.runners.model.TestTimedOutException: test timed out after 10000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at org.jbpm.test.listener.CountDownProcessEventListener.waitTillCompleted(CountDownProcessEventListener.java:55)
	at org.jbpm.test.functional.jobexec.AsyncTaskCallbackTest.testTaskCallback(AsyncTaskCallbackTest.java:89)
```

**Comment by pszubiak** [comment]
Jenkins retest this

**Comment by pszubiak** [comment]
I build this change locally and all tests passed. I think it's safe to merge.

**Pull request merged**
