### PR TITLE
[6.5.x] RHBPMS-4736 - QuartzSchedulerService increments NEXT_FIRE_TIME by tim…

### PR DESCRIPTION
**Pull request by mswiderski**
…eCycle regardless of current time when calling rescheduleJob() (#847)

rollup patch 6.4.4 backport

### CODE REVIEW

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by tsurdilo** [comment]
jenkins please retest this

**Comment by tsurdilo** [comment]
jenkins please retest this

**Comment by tsurdilo** [comment]
test fails on jenkins not related to this pr

**Pull request merged**
