### PR TITLE
[JBPM-9826] Getting potential owners for a case task

### PR DESCRIPTION
**Pull request by fjtirado**
**JIRA**:

[link](https://issues.redhat.com/browse/JBPM-9826)

**referenced Pull Requests**:

### CODE REVIEW

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by fjtirado** [comment]
jenkins run fdb

**Comment by fjtirado** [comment]
@elguardian failures are unrelated, I think you can review this one. 
Not sure if extra integration test is needed or not

**Comment by fjtirado** [comment]
jenkins retest this

**Review by elguardian — APPROVED** [review]
LGTM

**Review by afalhambra — COMMENTED** [review]
Great work!
I'm just missing a unit test for the jira. Would be nice if you could add one, here or as part of the integration repo.
Thanks!

**Review by gmunozfe — APPROVED** [review]
Looks good to me, great work @fjtirado!
Probably a test case could help for proper verification (it can be added later)

**Comment by baldimir** [comment]
Why this got merged without a test please? There were 2 requests for a test.

**Pull request merged**
