### PR TITLE
JBPM-8166: case modeler - register the assets into the workbench and process engine

### PR DESCRIPTION
**Pull request by xiezhang7**
Assembly:
https://github.com/kiegroup/drools/pull/2257
https://github.com/kiegroup/droolsjbpm-knowledge/pull/370
https://github.com/kiegroup/jbpm/pull/1440

### CODE REVIEW

**Comment by xiezhang7** [comment]
Hi @romartin , @wmedvede , @LuboTerifaj 

This is the pull request to fix the issue of case management item missing in "Process Instances" perspective, which was reported in [PR#370](https://github.com/kiegroup/droolsjbpm-knowledge/pull/370#issuecomment-463571643). Thanks to @wmedvede for providing the fix in [JBPM-8166](https://issues.jboss.org/browse/JBPM-8166?focusedCommentId=13695495&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13695495).

I also noticed "bpmn2" file extension is also hardcoded and used in [DroolsBuilder](https://github.com/kiegroup/droolsjbpm-tools/blob/99332400889fcbf9b0984100e905f6fdd4fa48e3/drools-eclipse/org.drools.eclipse/src/main/java/org/drools/eclipse/builder/DroolsBuilder.java#L365) and [jbpm-designer](https://github.com/kiegroup/jbpm-designer). But I am not sure if code in these repos affects the end-to-end flow. 

Thanks.

**Comment by wmedvede** [comment]
@xiezhang7 I think it's ok, but it'll be nice to have @mswiderski benediction. Could you please take a look @mswiderski ?
Final test I suggest you guys is to try to start the case using the REST API as Ivo suggests here https://issues.jboss.org/browse/JBPM-8166

Thanks

**Comment by romartin** [comment]
Please @mswiderski can you please take a quick look? That would be nice having it merged for tomorrow's release... thanks!

**Comment by wmedvede** [comment]
Jenkins execute full downstream build

**Comment by xiezhang7** [comment]
Hi @romartin , do we still need this pull request since case is not supposed to be shown in Process Definitions ?

**Comment by romartin** [comment]
@xiezhang7 aps, well I was not aware of that, so should we close it?

**Comment by xiezhang7** [comment]
Jenkins execute full downstream build

**Pull request merged**
