### PR TITLE
[7.59.x] [JBPM-9952] Include sort  processes by variables and tasks queries

### PR DESCRIPTION
**Pull request by fjtirado**
Removing sort from named query and sorting in memory according to the sorted list of ids

**JIRA**: 

[link](https://issues.redhat.com/browse/JBPM-9952)

### CODE REVIEW

**Review by afalhambra — APPROVED** [review]
LGTM

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
@elguardian could you review this?

**Review by elguardian — APPROVED** [review]
proper cherry pick

**Pull request merged**
