### PR TITLE
dependencyManagement section added after jboss_ip_bom replacement

### PR DESCRIPTION
**Pull request by gmunozfe**
@cristianonicolai @MarianMacik please review.
After jboss ip bom replacement, XES Main tests were failing due to incorrect versions of commons-cli library. New dependencyManagement section has been added to handle right ones.

### CODE REVIEW

**Comment by danielezonca** [comment]
@gmunozfe 
Hi, this other PR https://github.com/kiegroup/jbpm/pull/1507 fix another error introduced after jboss_ip_bom replacement (org.jbpm.executor.cdi.CDISimpleExecutorTest fails without that)

Can you please include that fix here so I can close the other PR?

**Comment by gmunozfe** [comment]
@danielezonca  done, check if it's alright

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by krisv** [comment]
Shouldn't we look at making sure we don't need to resolve an external url at runtime (isn't the xsd packaged on the server already, or for example by packaging the xsd ourselves?) so we can remove the external url?  We can do that in another follow-up PR if necessary.

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by danielezonca** [comment]
@krisv 
If I remember correctly @baldimir did something similar for `drools` repo. @baldimir Am I correct?

**Comment by baldimir** [comment]
@danielezonca @krisv it was @lucamolteni, who did that in Drools for changeset XSD. See Luca's PRs here https://github.com/kiegroup/drools/pull/2373.

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
@krisv the URL should be mapped to local resources as cdi-api artefact includes the xsd files, so as @MarianMacik verified it is resolved first locally.

**Pull request merged**
