### PR TITLE
[JBPM-9867] Changing getTaskInstances queries

### PR DESCRIPTION
**Pull request by fjtirado**
**JIRA**: 

[link](https://issues.redhat.com/browse/JBPM-9867)

### CODE REVIEW

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by elguardian** [comment]
Hi guys, I discussed this with @fjtirado 
It is not sematically the same query. I provided some feedback in the jira.

**Review by elguardian — CHANGES_REQUESTED** [review]
As dicusses some changes needed.

**Review by gmunozfe — APPROVED** [review]
Looks good to me, impeccable work @fjtirado !
I've added parameterized tests to check NONE audit mode with https://github.com/kiegroup/jbpm/pull/2005

**Comment by venkatvck** [comment]
This is blocking JBPM, RHPAM applications which deploy application with specific schema in shared DB. named native query does not look at any schema configurations (such as hibernate.default_schema or hibernate.schema_name_resolver ) to pick specific schema under the shared DB. We are blocked now from upgrading to latest versions.

**Pull request merged**
