### PR TITLE
[6.5.x] JBPM-6068 - RuntimeDataService task queries should use roles of the p…

### PR DESCRIPTION
**Pull request by tsurdilo**
…assed in user

### CODE REVIEW

**Comment by tsurdilo** [comment]
This needs to wait until the 6.4.4 release is done before merging.

**Comment by mswiderski** [comment]
@tsurdilo shouldn't we have this for 7.0.x branch too?

**Comment by tsurdilo** [comment]
@mswiderski I'm honestly not sure - @krisv can you say?

**Comment by krisv** [comment]
@mswiderski the 7.0.x branch should no longer be targeted, we're not planning any more releases from there, it was just for 7.0.0.Final

**Pull request merged**
