### PR TITLE
[JBPM-9888] Business Rules Task to allow dynamic definition of DMN Decision Name

### PR DESCRIPTION
**Pull request by elguardian**
Jira: https://issues.redhat.com/browse/JBPM-9888

### CODE REVIEW

**Review by jomarko — COMMENTED** [review]
Do we have some existing test for this change?

**Comment by elguardian** [comment]
@jomarko  this is a draft.

**Comment by elguardian** [comment]
Hi @jomarko  as @afalhambra has more expertise in the engine I would like him to review this PR instead of you.

**Comment by jomarko** [comment]
@elguardian please proceed without my review.

**Comment by elguardian** [comment]
Jenkins retest this please

**Comment by elguardian** [comment]
Jenkins retest this please

**Review by afalhambra — APPROVED** [review]
amazing work, well done @elguardian

**Pull request merged**
