### PR TITLE
BAQE-1696 - Change revapi to check against 7.48.0.Final

### PR DESCRIPTION
**Pull request by MarianMacik**
**JIRA:** [BAQE-1696](https://issues.redhat.com/browse/BAQE-1696)

depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1585

### CODE REVIEW

**Comment by MarianMacik** [comment]
jenkins retest this

**Review by afalhambra — APPROVED** [review]
LGTM

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
Test failure not related. `testSwimlaneWithMultipleActorsAssigned` seems to have been failing for a longer time. Trying once more.

Jenkins retest this

**Pull request merged**
