### PR TITLE
[incubator-kie-issues#1049] Add index to ProcessInstanceLog table to improve LogCleanupCommand performance

### PR DESCRIPTION
**Pull request by martinweiler**
Closes: https://github.com/apache/incubator-kie-issues/issues/1049

### CODE REVIEW

**Comment by akumar074** [comment]
Jenkins run fdb

**Review by pefernan — APPROVED** [review]

**Review by elguardian — APPROVED** [review]
LGTM

**Comment by elguardian** [comment]
Jenkins retest this pleases.

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
Hello @martinweiler @elguardian There are 5 test failures which are common in both FDB and PR checks and seems related with the change. Please take a look at it.

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by akumar074** [comment]
Jenkins run fdb

**Comment by elguardian** [comment]
@akumar074 this is work and good to go.

**Pull request merged**
