### PR TITLE
JBPM-7923 - Upgrade of hibernate to align with WildFly 14

### PR DESCRIPTION
**Pull request by mbiarnes**
(cherry picked from commit 38b75153305a5563c799723431b298b0a2783239)

replaced hibernate-jpa-2.1-api by javax.persistence-api

removed dependency since duplicated classes were found

### CODE REVIEW

**Comment by mswiderski** [comment]
@mbiarnes looks like there is a conflict here

**Comment by mswiderski** [comment]
@mbiarnes and I just noticed there is missing PR for droolsjbpm-integration repo...

**Comment by mbiarnes** [comment]
> @mbiarnes looks like there is a conflict here

**Comment by mbiarnes** [comment]
@mswiderski confilct resolved and missing PR of [droolsjbpm-integration](https://github.com/kiegroup/droolsjbpm-integration/pull/1703) added

**Pull request merged**
