### PR TITLE
RHDM-251 - Wildfly 11 upgrade

### PR DESCRIPTION
**Pull request by mareknovotny**
this is another round of reverted https://github.com/kiegroup/jbpm/pull/1122 and https://github.com/kiegroup/jbpm/pull/1113 from @nmirasch

### CODE REVIEW

**Comment by mareknovotny** [comment]
it seems that master has the same set of failed tests like this PR - https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/master/job/jbpm/552/

**Comment by mareknovotny** [comment]
What is worse I can't compile it locally now
```

**Comment by mswiderski** [comment]
@mareknovotny rebase your branch of droolsjbpm-knowledge

**Comment by mareknovotny** [comment]
ok, thanks for that advice.

**Comment by mswiderski** [comment]
@mareknovotny looks like PR job is running already with wildfly 11

```
-e -nsu -fae -B -T1C -Pwildfly11 clean install
```

then this branch does not have provide named that way in here https://github.com/mareknovotny/jbpm/tree/9e771e308e39b69704f037a971b00451af655f77/jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/resources/arquillian

I believe you should rename the wildfly10x to wildfly11x and then those EJB tests should work.

**Comment by MarianMacik** [comment]
Maciej is right, each container has its own arquillian.xml file.

**Comment by mswiderski** [comment]
and we are green here, thanks @mareknovotny

**Comment by MarianMacik** [comment]
Looks good, though jBPM Executor redesign is already present on master, isn't it? Why does GitHub show it?

**Comment by mareknovotny** [comment]
@MarianMacik that was my  pure rebase, so the order is a little confusing imho, but could be something different

**Comment by mareknovotny** [comment]
@mswiderski @MarianMacik I redid the rebase and commits are now in correct order

**Pull request merged**
