### PR TITLE
[JBPM-9316] Missing javax.xml.bind package with jdk11

### PR DESCRIPTION
**Pull request by gmunozfe**
**JIRA**: 

[JBPM-9316](https://issues.redhat.com/browse/JBPM-9316)

### CODE REVIEW

**Comment by gmunozfe** [comment]
Jenkins run fdb

**Comment by elguardian** [comment]
Jenkins run fdb

**Comment by elguardian** [comment]
Jenkins retest this please.

**Review by elguardian — APPROVED** [review]
LGTM, thx !

**Pull request merged**
