### PR TITLE
RHPAM-2120 Change the default strategy from Singleton to PerProcessIn…

### PR DESCRIPTION
**Pull request by bxf12315**
…stance

dependency on https://github.com/kiegroup/droolsjbpm-knowledge/pull/388

### CODE REVIEW

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by nmirasch** [comment]
Jenkins retest this please

**Comment by mswiderski** [comment]
@bxf12315 @cristianonicolai @MarianMacik see comments in jira as this might not be really needed in v7 anymore

**Comment by bxf12315** [comment]
won't fix.

**Comment by bxf12315** [comment]
won't fix.

**Pull request closed without merging**
