### PR TITLE
[JBPM-9614] Problem invoking WebServiceWorkItemHandler on Java 11

### PR DESCRIPTION
**Pull request by fjtirado**
Previous solution was not valid because URLS generated by
VFSResouceLoader has vfs protocol, which is not understood by cxf.

Hence I sligthly modified original approach. First list of
ResourceLoaders is obtained (package method). Then, depending on ResourceLoader type (we
are really only interested on Jar or VFS) we access different internal
private fields (since ResourceLoader unfortunately does not have getRootURL method).

In the case of VFS, we need extra logic to generate the right path to
jar file (went to parent and the append the jar name, as in original
fix)

**JIRA**: 

[link](https://issues.redhat.com/browse/JBPM-9614)

### CODE REVIEW

**Comment by fjtirado** [comment]
run fdb

**Comment by fjtirado** [comment]
jenkins run fdb

**Review by afalhambra — APPROVED** [review]
LGTM

**Comment by afalhambra** [comment]
failure test not related

**Comment by fjtirado** [comment]
Unrelated failure on fdb
@MarianMacik @elguardian I think we are ready to go with this one

**Review by MarianMacik — APPROVED** [review]

**Pull request merged**
