### PR TITLE
[JBPM-9895] Fix flaky tests at LocalTaskAuditWithDeadlineTest

### PR DESCRIPTION
**Pull request by gmunozfe**
**JIRA**: [JBPM-9895](https://issues.redhat.com/browse/JBPM-9895)

Cherry-pick from adc8aaf884bb967b2d25bb0072b4063b3ddcdf96

### CODE REVIEW

**Review by afalhambra — APPROVED** [review]
Nice one @gmunozfe! Thanks!

**Comment by gmunozfe** [comment]
@mareknovotny ready to merge

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
it would be also nice if you backport this fix into 7.59.x branch too

**Comment by gmunozfe** [comment]
@mareknovotny this is already merged at 7.59.x

**Pull request merged**
