### PR TITLE
[7.52.x] RHPAM-3496 - Custom task thumbnails are not consistent

### PR DESCRIPTION
**Pull request by Josephblt**
All icons are synchronized across projects. Equal sizes, images and naming pattern.

**JIRA**: [RHPAM-3496](https://issues.redhat.com/browse/RHPAM-3496)

**Referenced Pull Requests**:
https://github.com/kiegroup/jbpm-wb/pull/1488
https://github.com/kiegroup/kie-wb-common/pull/3616

**All Pull Requests need to be merged for this fix to work.**

**Business Central**: [WAR file](https://drive.google.com/file/d/13VqTL9mMT9kkuK9qaQy0fo6errRO2UM5/view?usp=sharing)

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins retest this

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hello @Josephblt ,

the issue is unfortunately not fixed:
- The icons are different in common Project in comparison with Case project.
- After the Custom tasks installation, the icons are changed. In addition, the changes are not  reflected with the first process/case opening.

I didn't test all scenarios since the main issue hasn't been fixed.

Thanks!

**Comment by romartin** [comment]
hey @Josephblt 
Can you please check @LuboTerifaj 's comments above?
Thanks!

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run fdb

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hi @Josephblt , @romartin ,

note, the legacy designer doesn't work as expected (see https://github.com/kiegroup/jbpm-designer/pull/902#pullrequestreview-636928422 for more details).

Therefore I would recommend to postpone merging and retest it with correct changes or without changes at all for legacy designer.

Thanks!

**Comment by Josephblt** [comment]
@romartin, @LuboTerifaj, done. Just closed the PR for the legacy-designer and updated the war. Ready for testing again.

**Comment by Josephblt** [comment]
Jenkins run cdb

**Review by LuboTerifaj — APPROVED** [review]
@Josephblt thanks for the update. It looks good to me now.

**Review by romartin — APPROVED** [review]

**Pull request merged**
