### PR TITLE
[6.5.x] Stabilize DeactivateDeploymentServiceWithSyncTest

### PR DESCRIPTION
**Pull request by MarianMacik**
Hi, @mswiderski,

here is the test stabilization we spoke about. Should I create a port to master/7.3.x with LinkedHashSet as well?

Thanks,

Marian

### CODE REVIEW

**Comment by mswiderski** [comment]
@MarianMacik I'd say we need this for 7.3.x and master as well. Thanks

**Comment by MarianMacik** [comment]
Jenkins retest this

**Comment by MarianMacik** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
this needs to be merged as it relates to https://github.com/kiegroup/jbpm/commit/6bba972979c75529092cb5fc8f72d959f999d708 that was already acks and causes test failures on some of the environment configuration.

**Pull request merged**
