### PR TITLE
[do not merge] Installer - upgrade wf10 --> wf11

### PR DESCRIPTION
**Pull request by nmirasch**
installer configuration files to upgrade wf10 -> wf11

### CODE REVIEW

**Comment by nmirasch** [comment]
@cristianonicolai, @bsremac could you take a look? Thanks!

**Comment by bsremac** [comment]
@cristianonicolai I hasted a little bit with the approval. I approved it based on diff content, not based on trying it out :( 
In both .xml files there are expected files _users.properties_ and _roles.properties_, which I don't know what they are. When tried to deploy kie-wb and kie-server, deploying failed for both because Wildfly couldn't find these files on the path.
When I renamed them in .xml file to _application-users.properties_ and _application-roles.properties_, both kie-wb and kie-server, got deployed but I couldn't login to kie-wb.

I hope it's just me and that I did something wrong. Just giving you some feedback, so you can try it out if you find time, before Neus and I get to the office.

**Comment by cristianonicolai** [comment]
@nmirasch @bsremac breaking changes from WildFly 11 have been reverted on master, we should hold this for now until everyone starts moving all projects towards this runtime.

**Comment by mareknovotny** [comment]
Could we include this into https://github.com/kiegroup/jbpm/pull/1122 ? as a whole bunch of changes for Wildfly 11?

**Comment by cristianonicolai** [comment]
@mareknovotny I think that would make sense. Perhaps @nmirasch  can send this PR to your branch?

**Comment by mareknovotny** [comment]
so I merged my PR changeset about wf11, I will merge this too now.

**Pull request merged**
