### PR TITLE
[JBPM-8252] Fail Fast ExecutorImpl

### PR DESCRIPTION
**Pull request by elguardian**
Check whether those sys properties can be empty or not, as well as found or not.
it does not stop kie-server from being deployed.

### CODE REVIEW

**Comment by mswiderski** [comment]
have you tried this on tomcat or spring boot deployments? I believe that it might fail as there is no JMS at all but property is on by default...

**Comment by elguardian** [comment]
@mswiderski you were right... tried with spring boot samples in droosjbpm-integration and it was failing. I added some logic
1) if the property is set, we cannot overwrite
2) if the property is not set, only consider default value if there is a java ee container underneath and false otherwise. I use standard  "java:app/AppName" to detect the container. It should not exist in servlet container as this only exists within an ear.

**Comment by mswiderski** [comment]
@elguardian the more I think about it and all the checks in the code I believe it's not worth it, @MarianMacik what do you guys think?

**Comment by MarianMacik** [comment]
Well, according to: https://stackoverflow.com/questions/3431357/how-can-i-config-module-and-application-name-for-jndi-lookups

appName is available only for ears and modulename is available also for wars.

The other thing is that we are changing the backward compatibility behaviour right now. I bet that a large portion of users don't use JMS and they didn't set up anything explicitly. They just rely on falling back to ThreadPool. As a compromise we might fail fast only if a user explicitly specified to use JMS, i.e. system property `org.kie.executor.jms` is set to true.

**Comment by elguardian** [comment]
@MarianMacik not really sure but before the change jms was used by default if the queue was found; e.g: EAP or any app server, but not other runtimes...
The problem here is that you cannot fail fast in environments like spring boot because by default before the use of jms was true but because of the fail fast this cannot be long the policy.

anycase if @mswiderski agrees with you I can change the behaviour.

**Comment by mswiderski** [comment]
I personally opt as dropping this change altogether ... seems to be rather complex logic for a feature that is kind of nice to have. Objections?

**Comment by elguardian** [comment]
none @mswiderski closing it.

**Pull request closed without merging**
