### PR TITLE
Log Stacktrace in ExecutorRunnable for Exceptions

### PR DESCRIPTION
**Pull request by ron-murhammer**
Log Stacktrace in ExecutorRunnable for Exceptions. Otherwise if there is some error then its very difficult to debug.

### CODE REVIEW

**Comment by tsurdilo** [comment]
ok to test'

**Comment by tsurdilo** [comment]
ok to test

**Comment by ron-murhammer** [comment]
Seems odd that adding a stack trace to a log message would break a unit test. Is this just a bad unit test?

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
This shouldn't be an issue. It is probably a random fail. Let's see if another build fixes that.

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by ron-murhammer** [comment]
It appears all of the recent PRs are showing a failed build. Probably indicates a failing or indeterminate unit test.

**Comment by tsurdilo** [comment]
Jenkins retest please

**Pull request merged**
