### PR TITLE
RHBPMS-4815 - Escape commas in LDAPUserGroupCallbackImpl filters

### PR DESCRIPTION
**Pull request by mswiderski**

### CODE REVIEW

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
@tarilabs @psiroky @mbiarnes any idea what can be the cause of this error:

`
05:42:15 [ERROR] [ERROR] Some problems were encountered while processing the POMs:

05:42:15 [FATAL] Non-resolvable parent POM for org.kie:kie-dmn-signavio:[unknown-version]: Could not find artifact org.kie:kie-dmn:pom:7.1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 3, column 11

05:42:15  @ 
05:42:15 [ERROR] The build could not read 1 project -> [Help 1]
05:42:15 org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:

05:42:15 [FATAL] Non-resolvable parent POM for org.kie:kie-dmn-signavio:[unknown-version]: 
Could not find artifact org.kie:kie-dmn:pom:7.1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 3, column 11`

**Comment by tarilabs** [comment]
There is a PR very recently merged: kiegroup/drools#1348
which introduces this new maven reactor module kie-dmn-signavio but I'm very surprised for this error because the PR was green.
I'm taking a look now.

**Comment by tarilabs** [comment]
I think what happened is that PR was green last week, in the meantime we bumped version on master, and then this PR was merged (with the parent coordinates version misaligned then).
I have raised kiegroup/drools#1374 for fixing it.
I taken care of actually reusing _this_ PR branch name so could mitigate being on hold due to this problem..

Jenkins test again

**Comment by tarilabs** [comment]
Jenkins test again please

**Comment by mswiderski** [comment]
Jenkins retest this

**Pull request merged**
