### PR TITLE
JBPM-6285 - Enable auto check License Headers for Java files for jBPM

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by tsurdilo** [comment]
* updates headers for all .java files
* adds RegexpHeader checkstyle only

@mswiderski @hasys this only adds the RegexpHeader check to jbpm - no other violations will be checked/reported. I have updated all .java files headers included in this pr also. Hope this is OK. Thanks.

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
test fails not related to this changes

**Pull request merged**
