### PR TITLE
JBPM-7923 - Upgrade of hibernate to align with WildFly 14

### PR DESCRIPTION
**Pull request by mswiderski**
depends on 
https://github.com/kiegroup/drools/pull/2138 
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/879

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by sutaakar** [comment]
@mswiderski Please remove AbstractBaseTest also from org/jbpm/process/workitem/bpmn2/JaxWSServiceTaskTest and org/jbpm/process/workitem/bpmn2/ServiceTaskTest

**Comment by sutaakar** [comment]
Also got ClassNotFoundException on BasicAuthRestWorkItemHandlerTest:
<details>
 <summary>ClassNotFoundException</summary>
org.jbpm.process.workitem.rest.BasicAuthRestWorkItemHandlerTest  Time elapsed: 0.035 sec  <<< ERROR!
java.lang.NoClassDefFoundError: javax/annotation/Priority
	at org.apache.cxf.jaxrs.utils.AnnotationUtils.getBindingPriority(AnnotationUtils.java:85)
	at org.apache.cxf.jaxrs.provider.ProviderFactory.getFilterPriority(ProviderFactory.java:1249)
	at org.apache.cxf.jaxrs.provider.ProviderFactory.mapInterceptorFilters(ProviderFactory.java:1221)
	at org.apache.cxf.jaxrs.provider.ServerProviderFactory.setProviders(ServerProviderFactory.java:270)
	at org.apache.cxf.jaxrs.provider.ProviderFactory.setUserProviders(ProviderFactory.java:793)
	at org.apache.cxf.jaxrs.AbstractJAXRSFactoryBean.setupFactory(AbstractJAXRSFactoryBean.java:332)
	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.setupFactory(JAXRSServerFactoryBean.java:237)
	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.create(JAXRSServerFactoryBean.java:182)
	at org.jbpm.process.workitem.rest.BasicAuthRestWorkItemHandlerTest.initialize(BasicAuthRestWorkItemHandlerTest.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.ClassNotFoundException: javax.annotation.Priority
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more

</details>

**Comment by mswiderski** [comment]
@sutaakar removed, thanks

**Comment by mswiderski** [comment]
looking into class not found now...

**Comment by mswiderski** [comment]
@sutaakar should be fixed now as well

**Comment by sutaakar** [comment]
@mswiderski Thanks, will check

**Comment by sutaakar** [comment]
Now getting test failure in FilteredKModuleDeploymentServiceTest.testMultipleRemotableInPojoJar.

From the log:
2018-11-08 14:07:16,062 [main|org.appformer.maven.integration.MavenRepository] WARN  Unable to resolve artifact: org.kie.soup:kie-soup-maven-support:7.14.0-20181107.101615-20
2018-11-08 14:07:16,426 [main|org.appformer.maven.integration.MavenRepository] WARN  Unable to resolve artifact: org.kie.soup:kie-soup-maven-support:7.14.0-20181107.101615-20
2018-11-08 14:07:16,427 [main|org.kie.scanner.MavenClassLoaderResolver] ERROR Dependency artifact not found for: org.kie.soup:kie-soup-maven-support:7.14.0-20181107.101615-20
2018-11-08 14:07:16,486 [main|org.drools.compiler.kie.builder.impl.AbstractKieProject] WARN  No files found for KieBase defaultKieBase
pom.xml : Unresolved dependency org.kie.soup:kie-soup-maven-support:7.14.0-20181107.101615-20

**Comment by mswiderski** [comment]
@sutaakar you can ignore that one, it does fail locally for some reason that cannot resolve artefact ... though it's there. For sure it's not related to hibernate upgrade 

Anyway looks like OptaPlanner is failing to compile here...

**Comment by mareknovotny** [comment]
Jenkins retest this

**Pull request closed without merging**
