### PR TITLE
Fixed deleteLogsByDate method to avoid issue with dates

### PR DESCRIPTION
**Pull request by afalhambra**
Changes to solve some issues when running Jenkins jobs due to w2k16 servers which are assigning same start date for several processes.

### CODE REVIEW

**Comment by afalhambra** [comment]
> congrats for your first contribution (of many more to come) to jbpm.

thanks! :)

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by afalhambra** [comment]
Jenkins retest this

**Comment by afalhambra** [comment]
Jenkin retest this

**Comment by afalhambra** [comment]
Jenkins retest this

**Pull request merged**
