### PR TITLE
[RHPAM-2526] Lots of queries against ContextMappingInfo when satisfying Milestone

### PR DESCRIPTION
**Pull request by elguardian**
depens on https://github.com/kiegroup/droolsjbpm-knowledge/pull/411

### CODE REVIEW

**Comment by elguardian** [comment]
testing another solution for this jira

**Comment by elguardian** [comment]
Jenkins retest this please

**Comment by mswiderski** [comment]
@elguardian since the issue originates from case mgmt I am thinking if we should somehow scoped the signal name - using external event listener for milestones but then make it add a case id into the signal name. That way the returned list of process instances will only be for given case instance. Wdyt?

**Comment by elguardian** [comment]
I will have a look at your idea.

**Comment by MarianMacik** [comment]
Can we close this PR?

**Pull request closed without merging**
