### PR TITLE
[7.5.x] JBPM-6828 - REST endpoint containers/{containerId}/processes/instance…

### PR DESCRIPTION
**Pull request by tsurdilo**
…s/{instanceId}/signals doesn't list boundary signals

### CODE REVIEW

**Comment by tsurdilo** [comment]
related jiras RHBA-392, RHBPMS-5120

**Comment by mswiderski** [comment]
7.5 branch is no longer updated so I don't think we need it here

**Comment by tsurdilo** [comment]
@krisv can you please comment on this. you mentioned we might need a pr for 7.5.x for consistency but it seems we don't as @mswiderski said. Please let us know what you think. Thanks.

**Comment by krisv** [comment]
@tsurdilo @mswiderski  7.5.x branch is still active, it's the RHDM 7.0.x product branch.  So yes, this should go in there.  It's 7.6.x that is no longer maintained.

**Comment by mareknovotny** [comment]
@tsurdilo don't forget to push this on master too

**Comment by mswiderski** [comment]
@krisv this does not have any value for RHDM as it is part of jBPM kie server extension which is disabled in RHDM.

@mareknovotny it's already on master

**Comment by krisv** [comment]
@mswiderski agreed, and I discussed this with Edson, we believe it might be better for consistency to cherry-pick all fixes we do to 6.5.x to more recent product branches (7.5.x in this case) and master of course, so our supported streams don't diverge.

**Pull request merged**
