### PR TITLE
Align Netty 4.x dependencies to Kie parent

### PR DESCRIPTION
**Pull request by almope**
Signed-off-by: Alberto Morales Pérez <almorale@redhat.com>

### CODE REVIEW

**Comment by elguardian** [comment]
@almope why is this on draft ?

**Comment by almope** [comment]
@elguardian hi! Thanks for reviewing and sorry, we were checking if there was a way to apply a more specific alignment instead of managing the aggregated netty-all jar. I've submitted another change and will move out the Draft mode once we're finished with checks on our side. Will ping you when it's ready.

Sorry for the inconvenience.

**Comment by almope** [comment]
@elguardian hi! This should be now ready. Thanks!

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by elguardian** [comment]
this is ok to go, @mareknovotny  ?

**Comment by mareknovotny** [comment]
there are 9 failures with OOM which can be or doesn't have to be related to this exclusion of netty

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by almope** [comment]
Jenkins execute full downstream build

**Comment by almope** [comment]
Closing this to avoid using `master` branch as source and prevent clashing on FDB

**Pull request closed without merging**
