### PR TITLE
[7.59.x] [JBPM-9920] Avoiding race condition between deployment and timer

### PR DESCRIPTION
**Pull request by fjtirado**
[JBPM-9920] Loading only the timers of the initialized deployment
Trying to avoid call to dispose in tests

**JIRA**:

[link](https://issues.redhat.com/browse/JBPM-9920)

### CODE REVIEW

**Comment by gmunozfe** [comment]
jenkins do fdb

**Comment by elguardian** [comment]
jenkins do fdb

**Comment by elguardian** [comment]
@gmunozfe  plz ack this

**Review by gmunozfe — APPROVED** [review]
Looks good to me, well done @fjtirado !

**Pull request merged**
