### PR TITLE
[JBPM-9589] Problem invoking WebServiceWorkItemHandler with EAP 7.3.5

### PR DESCRIPTION
**Pull request by fjtirado**
Changed reflection approach so it is based on public methods

**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9589)

### CODE REVIEW

**Comment by fjtirado** [comment]
Unrelated, jenkins test this again

**Review by elguardian — APPROVED** [review]
LGTM

**Review by gmunozfe — APPROVED** [review]
Looks good to me, great job @fjtirado !

**Comment by fjtirado** [comment]
@MarianMacik lets merge this one. 
Change in CXF can be make at any moment.

**Review by afalhambra — APPROVED** [review]
LGTM

**Review by MarianMacik — APPROVED** [review]

**Comment by fjtirado** [comment]
@kiegroup/gatekeepers please merge this

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by fjtirado** [comment]
@mareknovotny failure in FDB is unrelated. Anyway I do not think FDB is required for this one

**Comment by mareknovotny** [comment]
yes, Optaplanner does have compilation problem, but I would like to see at least some IT from droolsjbpm-integration where can this change be tested too.

**Comment by mareknovotny** [comment]
jenkins do fdb

**Pull request merged**
