### PR TITLE
[6.5.x] RHBPMS-5247 - Follow-up: Control which classes are registered…

### PR DESCRIPTION
**Pull request by MarianMacik**
… for serialization at kjar level
@elguardian FYI this limits serialization classes also on the deployment descriptor level in addition to your change in `KModuleDeploymentService`.

* limitSerializationClasses is now **true** also in `DeploymentDescriptorImpl`
* isEmpty() method and Merger has been aligned with 7.x stream
* Removed unstable and not relevant code in `FilterClassesAddedToDeployedUnitTest` - it was failing on some versions of IBM Java
* Added `@XmlRootElement` annotation to a Person class in one of kjars

@mareknovotny This also fixes tests which are currently failing. In case there is a CR2, we can make this a part of it.

### CODE REVIEW

**Comment by elguardian** [comment]
@MarianMacik I wasn't given any of this feedback.
Thanx for the fix.

**Comment by mareknovotny** [comment]
Jenkins test this please

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
finally PR builder jobs are working as expected ;)

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
@MarianMacik so is the failed test related to your changes? `org.jbpm.process.audit.query.AuditQueryTest.simpleNodeInstanceLogQueryBuilderTest`

**Comment by MarianMacik** [comment]
I don't think it is related, but I wanted to try PR check, so far no trigger after 45 minutes...

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
ok, it fails now in different test ;), I think we can merge it

**Pull request merged**
