### PR TITLE
@WidParameterValues support for wid processor

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by MarianMacik** [comment]
Nice! Just one question. Does this represent default values of parameters so users can still choose whatever they want or the only possible values? Thanks.

**Comment by tsurdilo** [comment]
@MarianMacik used to map a data input parameter to a predefined constant. in the process editor users will be presented a dropdown list of these values rather than a free text input box.

**Comment by tsurdilo** [comment]
Jenkins retest please

**Pull request merged**
