### PR TITLE
JBPM-8893 - Add full ISO8601 support for DateTimeUtils

### PR DESCRIPTION
**Pull request by SimonRinguette**
Added the support for parsing timer intermediate events with duration over a day

### CODE REVIEW

**Comment by kie-ci6** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by SimonRinguette** [comment]
@MarianMacik I've added the implementation + the test cases. Let me know if that works for you

**Comment by MarianMacik** [comment]
@SimonRinguette I have just slightly modified the test names and fixed the messages in assertions. Thank you very much for pointing this out! Good to know that Java has ISO8601 parsing split into 2 different classes. Once the build is green, I will merge it.

**Comment by SimonRinguette** [comment]
@MarianMacik Thanks

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
Rechecked the one failed test locally, seems to be unrelated. But will trigger it once more just to be sure.

jenkins retest this

**Comment by MarianMacik** [comment]
jenkins retest this

**Pull request merged**
