### PR TITLE
[BAQE-1833] Some projects are failing as persistence.xml was moved to a different location

### PR DESCRIPTION
**Pull request by afalhambra**
**[BAQE-1833](https://issues.redhat.com/browse/BAQE-1833)**: Some projects are failing as persistence.xml was moved to a different location

### CODE REVIEW

**Review by gmunozfe — APPROVED** [review]
Looks good to me, thanks for fixing this @afalhambra !

**Comment by afalhambra** [comment]
@mareknovotny could you please merge? thanks!

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by afalhambra** [comment]
Not related error in fdb... anyways, relaunching it again
Jenkins run fdb

**Comment by afalhambra** [comment]
Jenkins run fdb

**Comment by afalhambra** [comment]
test failure not related - running it once more
Jenkins run fdb

**Comment by afalhambra** [comment]
Jenkins run fdb

**Comment by afalhambra** [comment]
Jenkins do fdb

**Comment by afalhambra** [comment]
Jenkins do fdb

**Comment by afalhambra** [comment]
Finally green... :)
@mareknovotny please merge

**Pull request merged**
