### PR TITLE
[JBPM-6075] JBPM-Audit: fix failing tests

### PR DESCRIPTION
**Pull request by cimbalek**
Added cleaning tables in the beginning and after each test for AuditDeleteTest
Fixed comparing wrong values in CommandBasedAuditLogServiceTest

(cherry picked from commit fee7a89)

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
@cimbalek thanks, could you please send pr for 7.0.x as well?

@krisv or we don't plan to release anything more from 7.0.x?

**Comment by krisv** [comment]
@mswiderski @cimbalek we are not planning to release anymore from 7.0.x anymore, no need to do a PR there

**Comment by cimbalek** [comment]
@mswiderski @krisv Ok, thanks

**Pull request merged**
