### PR TITLE
JBPM-9494 - JBPM-9602 - Different icons

### PR DESCRIPTION
**Pull request by Josephblt**
All icons are synchronized across projects. Equal sizes, images and naming pattern.

**JIRA**:[JBPM-9494](https://issues.redhat.com/browse/JBPM-9494)
**JIRA**:[JBPM-9602](https://issues.redhat.com/browse/JBPM-9602)

**Referenced Pull Requests**:
https://github.com/kiegroup/jbpm-wb/pull/1487
https://github.com/kiegroup/kie-wb-common/pull/3615

**All Pull Requests need to be merged for this fix to work.**

**Business Central**: [WAR file](https://drive.google.com/file/d/1Ugx8YDnHWiUnN-GRhBfhRzqNS3FXCNSi/view?usp=sharing)

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb
Jenkins retest this

**Comment by Josephblt** [comment]
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins retest this

**Comment by Josephblt** [comment]
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins retest this

**Comment by Josephblt** [comment]
Jenkins retest this

**Comment by romartin** [comment]
jenkins retst this

**Comment by Josephblt** [comment]
Jenkins retest this

**Comment by Josephblt** [comment]
Jenkins retest this

**Comment by Josephblt** [comment]
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run fdb

**Review by romartin — COMMENTED** [review]
code updates are looking good
now just wating for the builds and for QE tests
thanks @Josephblt

**Comment by Josephblt** [comment]
Hello @romartin @LuboTerifaj. Builds are completed. The full build failed due to unrelated reasons. So I'm going to trigger it again. But anyway, this is ready to test. Just use the .war provided in the description. Thanks guys.

**Comment by Josephblt** [comment]
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run fdb

**Comment by LuboTerifaj** [comment]
The PR on 7.52.x branch: #1910

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hello @Josephblt ,

please let me know once the PR is ready for review again.

See more details in https://github.com/kiegroup/jbpm/pull/1910#pullrequestreview-632421472.

Thanks!

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb

**Comment by LuboTerifaj** [comment]
@Josephblt , what's the status of this PR? Can you please also link here all related PRs for master once it is ready to review? Thanks!

**Comment by Josephblt** [comment]
Jenkins run fdb

**Comment by Josephblt** [comment]
Hello @LuboTerifaj. Closed the PR for jbpm-designer and updated the .war. So everything is ready for testing. Remember, just like the RHPAM ones, the war is the same for all PR's no need test them individually. Thanks.

**Comment by Josephblt** [comment]
Jenkins run fdb

**Review by LuboTerifaj — APPROVED** [review]
It looks good to me. Thank you @Josephblt !

**Review by romartin — APPROVED** [review]

**Pull request merged**
