### PR TITLE
[JBPM-8103] Configure SonarCloud PR analysis for jBPM

### PR DESCRIPTION
**Pull request by rsynek**
Introducing new profiles used for code coverage measurement as a preparatory work for SonarCloud analysis, which will be available both daily and for each PR.

### CODE REVIEW

**Comment by rsynek** [comment]
As the new profiles could not have been activated in the PR check, failures are not connected with the change.

jenkins retest this

**Comment by MarianMacik** [comment]
Ignore the previous comment, it is probably a misconfiguration on the Jenkins.

**Comment by rsynek** [comment]
Below are the results for illustration:
https://sonarcloud.io/dashboard?id=org.jbpm%3Ajbpm

**Comment by rsynek** [comment]
jenkins retest this

**Comment by rsynek** [comment]
jenkins retest this

**Comment by rsynek** [comment]
@mswiderski would you kindly review and merge?

**Comment by rsynek** [comment]
> @rsynek I have really no expertise in this so my approval is sort of formality as @MarianMacik is fine with it

Thanks. Should you have any questions related to SonarCloud, feel free to reach out to me. Btw., it has been already merged also to kogito-runtimes.

**Comment by rsynek** [comment]
jenkins retest this

**Comment by rsynek** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
jenkins retest this

**Pull request merged**
