### PR TITLE
[JBPM-9783] Incorrect object type returned in a DMN business-rule task of a BPMN (RuleSetNode Instance)

### PR DESCRIPTION
**Pull request by elguardian**
Jira: https://issues.redhat.com/browse/JBPM-9774

### CODE REVIEW

**Review by jomarko — CHANGES_REQUESTED** [review]
Thank you for updates @elguardian . I was able to get tests working. However some cleanup is needed before we proceed with a merge. Please see my PR https://github.com/elguardian/jbpm/pull/7#pullrequestreview-683572956

As a last point there is one test fail, that I was not able to decide if there is an issue in the test itself, or we need a little bit more update the implementation.

```
[ERROR] Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.884 s <<< FAILURE! - in org.jbpm.workflow.instance.node.RuleSetInstanceTest
[ERROR] testProcessOutputs[7: Actual: <{code=1, message=abc, status=true}> Expected: <MyDataObject{message='abc', status=true, code=1}> Type: <org.jbpm.workflow.instance.node.RuleSetInstanceTest$MyDataObject>](org.jbpm.workflow.instance.node.RuleSetInstanceTest)  Time elapsed: 0.01 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<"[org.jbpm.workflow.instance.node.RuleSetInstanceTest$MyDataObject]"> but was:<"[java.util.HashMap]">
```

**Comment by elguardian** [comment]
@jomarko  it is a class loader problem.

**Comment by jomarko** [comment]
@elguardian the PR build failed. We need to update the license of the new file.

```
12:47:35  [ERROR] src/main/java/org/jbpm/process/instance/impl/util/ComparablePeriodSerializer.java:[8] (header) RegexpHeader: Line does not match expected header line of '^ \*     http:\/\/www\.apache\.org\/licenses\/LICENSE-2\.0$'.
```

**Comment by elguardian** [comment]
failures not related (random test failure i job executor)

**Comment by jomarko** [comment]
Failed test:
```
org.jbpm.executor.impl.jms.JmsAvaiableJobExecutorTest.testAsyncAuditErrorProducer
```

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by jomarko** [comment]
Jenkins do fdb

**Comment by elguardian** [comment]
@jomarko this does not affect integration so fdb is unnecessary.

**Comment by elguardian** [comment]
fdb will be broken as integration has some test karaf failures related to 
https://github.com/kiegroup/droolsjbpm-integration/pull/2514

**Comment by elguardian** [comment]
Jenkins do fdb

**Review by jomarko — APPROVED** [review]
@elguardian hello, sorry for delays with review.

I can confirm the mapping now works on business central platform. I was able to deploy a project on kie server, where a BPMN process mapped DMN results into custom java data type, without need to handle returned DMN map manually.


However it seems to me the same scenario still doesn't work on kogito. Could you please have a look? https://issues.redhat.com/browse/KOGITO-5366

From my point of view this PR can be merged (once jenkins is green), however I think we still can not resolve the related BAPL.

Thank you.

**Comment by elguardian** [comment]
@jomarko BAPL are corresponding to RHPAM not to KOGITO. they are product so lifecycle are not attached to if this is in kogito or not. (once this is merged) related BAPL should marked as resolved.
This is the lifecycle of RHPAM/RHDM feature BAPL.

**Comment by jomarko** [comment]
@elguardian ok, with 7.11 we start to support also kogito decision management on product level, in other words we track in RHDM/RHPAM also jiras targeting kogito platform, as this relates both BPMN and DMN, let me recheck with team, how to proceed with BAPL.

**Comment by elguardian** [comment]
@lazarotti can you jump into this situation plz and clarify the lifecycle of jbpm engine BAPL ?

**Comment by elguardian** [comment]
Out of memory error not related ... and again the errors from karaf.

**Comment by elguardian** [comment]
Jenkins do fdb

**Comment by elguardian** [comment]
Jenkins do fdb

**Comment by elguardian** [comment]
failures not related in fdb. once belonges to UI the other one belongs to env issue

**Pull request merged**
