### PR TITLE
[7.44][RPHAM-3106] Getting error then try to generate classes from WSDL fil…

### PR DESCRIPTION
**Pull request by fjtirado**
…e (#1762)

Generating custom class loader with list of jars in case
ModuleClassLoader is found in hierachy

**JIRA**: 

[RHPAM-3106](https://issues.redhat.com/browse/RHPAM-3106)

### CODE REVIEW

**Comment by mareknovotny** [comment]
could you add into PR set also the test from https://github.com/kiegroup/droolsjbpm-integration/pull/2267 ?

**Comment by afalhambra** [comment]
> could you add into PR set also the test from [kiegroup/droolsjbpm-integration#2267](https://github.com/kiegroup/droolsjbpm-integration/pull/2267) ?

@fjtirado @mareknovotny 

I think this PR is duplicated, if I'm not wrong. Please check https://github.com/kiegroup/jbpm/pull/1762. 

If so, please close this. https://github.com/kiegroup/droolsjbpm-integration/pull/2267 is based on the assumption that https://github.com/kiegroup/jbpm/pull/1762 is already there, otherwise it will fail.

**Comment by afalhambra** [comment]
> could you add into PR set also the test from [kiegroup/droolsjbpm-integration#2267](https://github.com/kiegroup/droolsjbpm-integration/pull/2267) ?

Done - https://github.com/kiegroup/droolsjbpm-integration/pull/2297

**Review by afalhambra — APPROVED** [review]
Looks good to me - already merged in master.

**Comment by mareknovotny** [comment]
thanks @afalhambra. While the backport now is created by you, I was looking to have it from one author and with the same branch to have both tested in CI. Our CI approaches the same author/branch only, so if you have that from 2 authors or even one author on the different named branches Jenkins/GA can't guess and build/test it together.

**Comment by mareknovotny** [comment]
marking as DO_NOT_MERGE until 7.44.x branch is open

**Comment by afalhambra** [comment]
> thanks @afalhambra. While the backport now is created by you, I was looking to have it from one author and with the same branch to have both tested in CI. Our CI approaches the same author/branch only, so if you have that from 2 authors or even one author on the different named branches Jenkins/GA can't guess and build/test it together.

Ok, I see. Didn't know that. Let me know if you need some additional change from my side for that PR. Thanks!

**Review by jiripetrlik — APPROVED** [review]

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
