### PR TITLE
BAQE-440: Use DBCP for jBPM in container tests on Tomcat

### PR DESCRIPTION
**Pull request by rsynek**
Shows an integration of DBCP pooling data source into jBPM in container tests on Tomcat.

### CODE REVIEW

**Comment by mswiderski** [comment]
@rsynek how does this PR relate to https://github.com/kiegroup/jbpm/pull/1217?

**Comment by rsynek** [comment]
@mswiderski while #1217 focuses on unit tests only, this one brings the DBCP integration to tests on Tomcat. It shouldn't depend on #1217, but very likely it depends on the same fixes in https://github.com/kiegroup/drools/pull/1939.

**Comment by rsynek** [comment]
jenkins retest this

**Comment by rsynek** [comment]
jenkins retest this

**Comment by rsynek** [comment]
@mswiderski Ready to merge once the PR check passes and https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/853 is merged.

**Comment by rsynek** [comment]
jenkins retest this

**Pull request merged**
