### PR TITLE
Jbpm installer wildfly 11

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
@mbiarnes why this is targeting 7.5.x branch?

**Comment by mswiderski** [comment]
@mareknovotny shall this go into 7.5.x?

**Comment by mareknovotny** [comment]
@mswiderski this is probably some backport, but we don't need it now. Next version will use master anyway.
Or @mbiarnes is there any other reason to merge this into 7.5.x?

**Pull request closed without merging**
