### PR TITLE
Stabilize log clean tests considering repeated startDates

### PR DESCRIPTION
**Pull request by gmunozfe**
Need to stabilize w2k16 pipelines (faster CPU) where tests using process startDate to delete logs are not considering that more than one process may have the same startDate.

### CODE REVIEW

**Comment by gmunozfe** [comment]
Jenkins retest this

**Comment by gmunozfe** [comment]
Jenkins retest this

**Comment by MarianMacik** [comment]
Jenkins retest this

**Comment by gmunozfe** [comment]
Jenkins retest this

**Comment by gmunozfe** [comment]
Jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
Thanks @gmunozfe!

**Pull request merged**
