### PR TITLE
JBPM-6890: Adding the customTaskID as a unique identifier for an active

### PR DESCRIPTION
**Pull request by mcivantos-tribalyte**
Added processInstanceDescription as a businessId

### CODE REVIEW

**Comment by mswiderski** [comment]
ok to test

**Comment by mswiderski** [comment]
@mcivantos-tribalyte I had to revert this commit as it was causing compilation errors in droolsjbpm-integration module. Could you please create it once again, and please also add references between PRs if there are any so they won't be merged separately as it can cause problems (like in this case)

**Comment by mcivantos-tribalyte** [comment]
@mswiderski  Ok. I'll send again and link to the other one related to it.

**Comment by mcivantos-tribalyte** [comment]
@mswiderski Here, you have the new one
https://github.com/kiegroup/jbpm/pull/1148

**Pull request merged**
