### PR TITLE
[JBPM-9920] Avoiding race condition between deployment and timer

### PR DESCRIPTION
**Pull request by fjtirado**
**JIRA**: 

[link](https://issues.redhat.com/browse/JBPM-9920)

### CODE REVIEW

**Comment by albfan** [comment]
tested. this definitely fix the issue

**Comment by elguardian** [comment]
this fixes the problem upon restart of the server. This scenarios needs to be verify with the user to see if this is really what is going on.

**Comment by elguardian** [comment]
Jenkins retest this please

**Comment by albfan** [comment]
Martin, just tested it and commit 9e9e39076
<https://github.com/kiegroup/jbpm/pull/2044/commits/9e9e39076121cd9ad276908811a105c93a8c197a>
works
correctly for me (with or without restart)

**Comment by gmunozfe** [comment]
jenkins retest this

**Pull request merged**
