### PR TITLE
RHPAM-3897: switch to jboss-transaction-spi-jakarta

### PR DESCRIPTION
**Pull request by almope**
Signed-off-by: Alberto Morales Perez <almorale@redhat.com>

**JIRA**: [RHPAM-3897](https://issues.redhat.com/browse/RHPAM-3897)

**referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1768
* https://github.com/kiegroup/drools/pull/3832
* https://github.com/kiegroup/droolsjbpm-integration/pull/2602
* https://github.com/kiegroup/jbpm-work-items/pull/215
* https://github.com/kiegroup/kie-jpmml-integration/pull/64
* https://github.com/kiegroup/optaplanner/pull/1574
* https://github.com/kiegroup/kie-soup/pull/227
* https://github.com/jboss-integration/rhba-installers/pull/92

### CODE REVIEW

**Comment by almope** [comment]
Jenkins PR check passed the build but failed archiving artifacts with the following which is unrelated to the change but with the CI config.
```
[2021-09-13T19:07:57.049Z] Archiving artifacts
[2021-09-13T19:07:59.008Z] java.lang.InterruptedException: no matches found within 10000
```

**Comment by almope** [comment]
**Important**: Needs to be checked with the profile `tomcat9`

**Comment by gmunozfe** [comment]
@almope please edit 1st comment with the right link to the Jira and the referenced PRs:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1768, https://github.com/kiegroup/droolsjbpm-integration/pull/2602, https://github.com/jboss-integration/rhba-installers/pull/92

**Review by elguardian — APPROVED** [review]
LGTM

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by almope** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
timed out
jenkins retest this

**Comment by almope** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
jenkins retest this please

**Pull request merged**
