### PR TITLE
[7.3.x] JBPM-6417 - Kie Server rest Signals API does not resolve mvel express…

### PR DESCRIPTION
**Pull request by tsurdilo**
…ions

### CODE REVIEW

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by tsurdilo** [comment]
@mswiderski you know why this test is failing ? runs ok locally

**Comment by tsurdilo** [comment]
Jenkins retest please

**Pull request merged**
