### PR TITLE
BXMSPROD-710 Jenkinsfile modification. Just for testing purposes (to create a PR)

### PR DESCRIPTION
**Pull request by Ginxo**
BXMSPROD-710
DO NOT MERGE.

### CODE REVIEW

**Comment by Ginxo** [comment]
Jenkinstest execute full downstream build

**Comment by Ginxo** [comment]
Jenkinstest execute full downstream build

**Comment by mareknovotny** [comment]
is this PR forgotten or why it is just for jbpm repository?

**Comment by Ginxo** [comment]
@mareknovotny this should be kept as it is now until up/downstream kie-parent project one is stable

**Pull request closed without merging**
