### PR TITLE
[7.5.x] RHPAM-1154 - Signal on boundary event causes an unwanted event listener message

### PR DESCRIPTION
**Pull request by elguardian**
the cancel method should avoid firing and after node
left event causing an unwanted log.

cherry picked from #1226

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
@mareknovotny shall this be merged? does it target any patch release?

**Comment by mareknovotny** [comment]
@mswiderski no, if we have this on master we are ok and done.

**Pull request closed without merging**
