### PR TITLE
DROOLS-1629 - Allow multiple ObjectMarshallingStrategy of the same class

### PR DESCRIPTION
**Pull request by mswiderski**

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by mswiderski** [comment]
I think it can be merged without full downstream as it only changes tests so it has no way to affect any other repo

**Comment by hasys** [comment]
@mswiderski it is more about the check that it will fix Full build :)

**Pull request merged**
