### PR TITLE
Cover all DMN built in types

### PR DESCRIPTION
**Pull request by jomarko**
Cover nested structures

Format dmn files

Adapt tests due to new ComparablePeriodSerializer

Move tests to proper module

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[JBPM-9774](https://issues.redhat.com/browse/JBPM-9774)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by elguardian** [comment]
test failing for me regarding namespace and decision model

**Comment by elguardian** [comment]
not really sure what are you trying rule set node instance

https://github.com/kiegroup/jbpm/blob/master/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/RuleSetNodeInstance.java#L321-L323

that was done by a community jira JBPM-9452

**Comment by elguardian** [comment]
superseeded https://github.com/kiegroup/jbpm/pull/1953

**Comment by jomarko** [comment]
Closing due to https://github.com/kiegroup/jbpm/pull/1952#issuecomment-860807941. The work will continue via #1953

**Pull request closed without merging**
