### PR TITLE
[incubator-kie-issues-646] Duplicate timer created for Task SLA Due date with AsyncMode env setting

### PR DESCRIPTION
**Pull request by elguardian**
issue: https://github.com/apache/incubator-kie-issues/issues/646

### CODE REVIEW

**Comment by elguardian** [comment]
the async node access the metadata of the node being wrapped causing the node itself registering an SLA twice
once when it is scheduled and the other one when the node itself is triggered.

**Review by martinweiler — APPROVED** [review]
Nice and clean fix, thanks @elguardian

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by elguardian** [comment]
@gmunozfe need this to be reviewed.

**Review by gmunozfe — APPROVED** [review]
Looks good to me, great fix @elguardian !

**Comment by mareknovotny** [comment]
could you look at sonar problem at https://sonarcloud.io/project/issues?resolved=false&types=BUG&pullRequest=2352&id=org.jbpm%3Ajbpm&open=AYtrkrLmJ56keKDifEdB ?

**Comment by elguardian** [comment]
@martinweiler this https://github.com/kiegroup/jbpm/pull/2355 should be in when creating the patch as well.

**Pull request merged**
