### PR TITLE
[BAQE-1562] Follow-up regarding jbpm performance test for search variables API scenario

### PR DESCRIPTION
**Pull request by afalhambra**
**[BAQE-1562](https://issues.redhat.com/browse/BAQE-1562)**: Follow-up regarding jbpm performance test for search variables API scenario

### CODE REVIEW

**Review by MarianMacik — APPROVED** [review]

**Comment by afalhambra** [comment]
@kiegroup/gatekeepers could you please merge?

**Comment by mareknovotny** [comment]
@afalhambra sonar reports unused import https://github.com/kiegroup/jbpm/blob/1693c07ea17b2b1490b5ba505fc70bcc1ac55c82/jbpm-test/src/main/java/org/jbpm/test/services/AbstractServicesTest.java#L21 ;)

**Comment by afalhambra** [comment]
> jbpm/jbpm-test/src/main/java/org/jbpm/test/services/AbstractServicesTest.java

Done - Thanks @mareknovotny

**Comment by mareknovotny** [comment]
as AbstractKieServicesTest class is used in https://github.com/kiegroup/kie-jpmml-integration/blob/master/jbpm-recommendation-pmml-logistic-regression/src/test/java/org/jbpm/prediction/pmml/PMMLLogisticRegressionPredictionServiceProcessTest.java I will fire fdb too

jenkins do fdb

**Comment by afalhambra** [comment]
fdb is green - @kiegroup/gatekeepers can you please merge?

**Pull request merged**
