### PR TITLE
JBPM - 6641 - Return the input&output data of tasks when using Advanced Queries

### PR DESCRIPTION
**Pull request by mcivantos-tribalyte**
Added updates in data/metadata of task in the TASKEVENT table.

### CODE REVIEW

**Comment by tsurdilo** [comment]
ok to test

**Comment by mswiderski** [comment]
@mcivantos-tribalyte this is already covered in this PR https://github.com/kiegroup/jbpm/pull/1089/files#diff-96f9a741dfc90d35e4aa0f49da0af8a8R712

moreover we should not add updated event on task inputs as they are usually added when task is created so you would end up in two events for single operation which in my opinion is wrong.

So overall, this PR duplicates #1089

**Comment by mcivantos-tribalyte** [comment]
@mswiderski You are right. I would only suggest adding on your PR the update of the lastModificationDate in AuditTaskImpl after this https://github.com/kiegroup/jbpm/pull/1089/files#diff-96f9a741dfc90d35e4aa0f49da0af8a8R712
Or I could change this PR, when your PR is merged in order to updated the Audit task info.

**Comment by mswiderski** [comment]
@mcivantos-tribalyte good point, added that to that PR

**Comment by mswiderski** [comment]
closing as it is covered by #1089

**Pull request closed without merging**
