### PR TITLE
AF-2811: Required Process Variable Tags shouldn't be accepted in form…

### PR DESCRIPTION
**Pull request by akumar074**
…s when empty

(cherry picked from commit e1887f9195abc090fd3441b64b84c8ced9a83971)

**JIRA**: 
[AF-2811](https://issues.redhat.com/browse/AF-2811)
[RHPAM-3047](https://issues.redhat.com/browse/RHPAM-3047)

**referenced Pull Requests**:
Original PR : https://github.com/kiegroup/jbpm/pull/1895

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by elguardian** [comment]
this si fine but branch is blocked to put anything in there till release is done.

**Review by tomasdavidorg — APPROVED** [review]

**Comment by akumar074** [comment]
Hi @elguardian , Is there any failure in JBPM 7.52.x branch? This issue targets 7.11 which needs to be in 7.52.x

**Comment by akumar074** [comment]
Jenkins retest this

**Comment by akumar074** [comment]
Hi @elguardian , is it good to merge the PRs on 7.52.x now?

**Pull request merged**
