### PR TITLE
[JBPM-10103] Fix order in Servicesorm.xml to pass validation

### PR DESCRIPTION
**Pull request by albfan**
**JIRA**: [JBPM-10103](https://issues.redhat.com/browse/JBPM-10103)

Using springboot application from start.jbpm.org orm xml is validated. It needs the tags in order:

- named-query
- named-native-query
- sql-resultset-mapping

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by gmunozfe** [comment]
@albfan is it ready to be reviewed?

**Comment by albfan** [comment]
@gmunozfe It should be ready now, with issue related to JBPM no RHPAM

**Review by gmunozfe — APPROVED** [review]
Looks good to me, excellent work @albfan !

**Comment by gmunozfe** [comment]
@albfan you should also backport it to 7.67.x and 7.67.x-blue branches.

**Comment by albfan** [comment]
Working on it!

**Comment by albfan** [comment]
@gmunozfe #2179 and #2180

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
closing as we downgraded to SB 2.5.x

**Comment by albfan** [comment]
Probably this validación affects 2.5.x too.

It should be safe to integrate It as soon as possible.

**Comment by mareknovotny** [comment]
ok, if you think that this is still valid even for 2.5.x re-open your PRs,but change jira description to show the real issue. Thanks in advance

**Comment by albfan** [comment]
Will check and reopen if so

**Pull request closed without merging**
