### PR TITLE
JBPM-10058 Task form with LocalDateTime datatype displays time format…

### PR DESCRIPTION
**Pull request by bxf12315**
… even when the option is unflagged

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by jstastny-cz — CHANGES_REQUESTED** [review]
Please add tests.

**Comment by bxf12315** [comment]
> Hey @bxf12315 I think this change is a bit drastic. I'd say that this should be addressed in the kie-server side, I think this class is too low level. However, if you still think that the change is needed I'd go for adding a new class for the specific type.


> Hey @bxf12315 I think this change is a bit drastic. I'd say that this should be addressed in the kie-server side, I think this class is too low level. However, if you still think that the change is needed I'd go for adding a new class for the specific type.

1 user bc start process, playload:
`<map>
  <entry>
    <string>bbdate</string>
    <null/>
  </entry>
  <entry>
    <string>bdate</string>
    <local-date-time>2022-05-10T18:50:00</local-date-time>
  </entry>
  <entry>
    <string>name</string>
    <string>gg</string>
  </entry>
</map>
`
2 use kie-server form start process, playload:
`{"bdate":"2022-05-09T12:54","name":"asdf","bbdate":"2022-05-10T00:00"}`

3 we use code [1] to unmarshal playload, so. when we met json( kie-server form), we do not know the param's objecttype, 
so it's String.
4 for my side, better way is create a new type "dateObject", let can handle object and string. but if we add new type, it's not related to form module and jbpm and jbpm-wb code, it's also related to designer's code,it will be big. change..
My code just a workaround way.

[1] https://github.com/kiegroup/droolsjbpm-integration/blob/88f418210a55941be48ae0ca6af6ff33d612d7fd/kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ProcessServiceBase.java#L112

**Comment by pefernan** [comment]
@bxf12315 I'm not an expert on this layer, but I see other `DataTypes`, if there's no way to solve the issue in kie-server, maybe creating a specific `LocalDateDataType` would make more sense than modifying the `ObjectDataType` that is extended by other `DataTypes`, however I'd like a better assesment from someone who has deeper knowledge of this area... @elguardian are you the one?

**Comment by elguardian** [comment]
superseeded by https://github.com/kiegroup/droolsjbpm-integration/pull/2768

**Pull request closed without merging**
