### PR TITLE
[6.5.x] RHBPMS-5182 - Methods of org.jbpm.services.task.lifecycle.listeners.T…

### PR DESCRIPTION
**Pull request by mswiderski**
…askLifeCycleEventListener are not called

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by mareknovotny** [comment]
@tsurdilo is this PR failing always on the same set of tests?

**Comment by mareknovotny** [comment]
Jenkins retest please

**Comment by MarianMacik** [comment]
Jenkins retest this

**Comment by MarianMacik** [comment]
@mareknovotny I believe the issue was with jbpm-container-test and Maven parallel build. I have hopefully fixed it as a part of #1265.

**Comment by mareknovotny** [comment]
Jenkins retest this

**Comment by MarianMacik** [comment]
@mareknovotny I believe it is.

**Pull request merged**
