### PR TITLE
[JBPM-9705] Able to execute process admin REST API's without valid co…

### PR DESCRIPTION
**Pull request by abhijithumbe**
…ntainerID

**Thank you for submitting this pull request**

**JIRA**: _(https://issues.redhat.com/browse/JBPM-9705)_

### CODE REVIEW

**Comment by krisv** [comment]
ok to test

**Comment by elguardian** [comment]
1) this is not backward compatible. removed old methos. possible breaking user space code.
2) does not take into account aliases at kie server level
3) not a single test in something so delicate.

**Comment by elguardian** [comment]
Jenkins retest this please

**Comment by abhijithumbe** [comment]
@elguardian  Thank you for feedback, working on it.

**Comment by abhijithumbe** [comment]
@elguardian Required changes are done. Please take a look.

**Comment by abhijithumbe** [comment]
depends on [#2464](https://github.com/kiegroup/droolsjbpm-integration/pull/2464)

**Comment by elguardian** [comment]
Jenkins retest this please.

**Pull request closed without merging**
