### PR TITLE
[JBPM-8801] Process instance assign first potencial actor to field "created by" when it is empty in process definition

### PR DESCRIPTION
**Pull request by elguardian**
remove default createdBy assignment to a task

### CODE REVIEW

**Comment by gmunozfe** [comment]
Some AssertEquals have to be replaced by AssertNull in tests:

https://github.com/kiegroup/jbpm/blob/5ab9f0614f8e002b6aa7942280023a6e141fd471/jbpm-human-task/jbpm-human-task-workitems/src/test/java/org/jbpm/services/task/wih/util/PeopleAssignmentHelperTest.java#L137

https://github.com/kiegroup/jbpm/blob/5ab9f0614f8e002b6aa7942280023a6e141fd471/jbpm-human-task/jbpm-human-task-workitems/src/test/java/org/jbpm/services/task/wih/util/PeopleAssignmentHelperTest.java#L166

https://github.com/kiegroup/jbpm/blob/5ab9f0614f8e002b6aa7942280023a6e141fd471/jbpm-human-task/jbpm-human-task-workitems/src/test/java/org/jbpm/services/task/wih/util/PeopleAssignmentHelperTest.java#L179

https://github.com/kiegroup/jbpm/blob/5ab9f0614f8e002b6aa7942280023a6e141fd471/jbpm-human-task/jbpm-human-task-workitems/src/test/java/org/jbpm/services/task/wih/util/PeopleAssignmentHelperTest.java#L210

https://github.com/kiegroup/jbpm/blob/5ab9f0614f8e002b6aa7942280023a6e141fd471/jbpm-human-task/jbpm-human-task-workitems/src/test/java/org/jbpm/services/task/wih/util/PeopleAssignmentHelperTest.java#L223


https://github.com/kiegroup/jbpm/blob/a1b088375a313179ec3bcee27c6f92f8923dce74/jbpm-human-task/jbpm-human-task-workitems/src/test/java/org/jbpm/services/task/wih/HTWorkItemHandlerBaseTest.java#L603

**Comment by elguardian** [comment]
this is ok to test.

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
@gmunozfe are we ok with merging this?

**Pull request merged**
