### PR TITLE
 JBPM-7040 - ExecutorEventSupportEJBImpl EJB does not resolve on WLS and WAS

### PR DESCRIPTION
**Pull request by MarianMacik**
Hi, @mswiderski,

here is the PR about making Executor EJBs work on WAS/WLS. I have tested it on EAP/WAS/WLS locally, so it should be OK now. Should I create an upstream JIRA for this issue too?

### CODE REVIEW

**Comment by mswiderski** [comment]
@MarianMacik yes, please add jira and update commit message, thanks

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by MarianMacik** [comment]
jenkins retest this

**Pull request merged**
