### PR TITLE
[6.5.x] RHBPMS-5167 - Not possible to migrate process with recurring timer (#…

### PR DESCRIPTION
**Pull request by mswiderski**
…1234)

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by tsurdilo** [comment]
@mswiderski is this safe to be merged?

**Pull request merged**
