### PR TITLE
fixed wildfly18 left-overs

### PR DESCRIPTION
**Pull request by mbiarnes**
there were some files still pointing to wildfly18 - or some files with wildlfy18 in its name -
this corrupted the jbpm-installer

### CODE REVIEW

**Comment by mbiarnes** [comment]
Attention: the changes in  jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/pom.xml and  jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/pom.xml  are the same as in PR: https://github.com/kiegroup/jbpm/pull/1696 - so I will remove them form this one

**Comment by mareknovotny** [comment]
i am not really sure that renaming the standalone-full.xml configurations are ok, as there are changed namespaces in Wildfly 19.1.0.Final

**Comment by mareknovotny** [comment]
so going in history back the config files are from Wildfly 11 and simple comparison gives the patch:
```
--- /home/mnovotny/apps/wildfly-11.0.0.Final/standalone/configuration/standalone.xml
+++ /home/mnovotny/projects/git/KIEGROUP/jbpm/jbpm-installer/src/main/resources/standalone-wildfly-18.0.1.Final.xml
@@ -50,10 +50,10 @@
                 </server-identities>
                 <authentication>
                     <local default-user="$local" allowed-users="*" skip-group-loading="true"/>
-                    <properties path="application-users.properties" relative-to="jboss.server.config.dir"/>
+                    <properties path="users.properties" relative-to="jboss.server.config.dir"/>
                 </authentication>
                 <authorization>
-                    <properties path="application-roles.properties" relative-to="jboss.server.config.dir"/>
+                    <properties path="roles.properties" relative-to="jboss.server.config.dir"/>
                 </authorization>
             </security-realm>
         </security-realms>
@@ -146,6 +146,13 @@
                     <security>
                         <user-name>sa</user-name>
                         <password>sa</password>
+                    </security>
+                </datasource>
+                <datasource jta="true" jndi-name="java:jboss/datasources/jbpmDS" pool-name="H2DS" enabled="true" use-java-context="true" use-ccm="true">
+                    <connection-url>jdbc:h2:tcp://localhost/~/jbpm-db;MVCC=TRUE</connection-url>
+                    <driver>h2</driver>
+                    <security>
+                        <user-name>sa</user-name>
                     </security>
                 </datasource>
                 <drivers>
@@ -421,6 +428,8 @@
                         <login-module code="RealmDirect" flag="required">
                             <module-option name="password-stacking" value="useFirstPass"/>
                         </login-module>
+                        <login-module code="org.kie.security.jaas.KieLoginModule" flag="optional" module="deployment.jbpm-console.war"/>
+                        <login-module code="org.kie.security.jaas.KieLoginModule" flag="optional" module="deployment.jbpm-casemgmt.war"/>
                     </authentication>
                 </security-domain>
                 <security-domain name="jboss-web-policy" cache-type="default">
```
so you need to take config files from Wildfly 19.1.0.Final and apply this additional jbpm related configuration for all standallone-wildfly*.xml. Another step needs to be done also on EAP 7.0.0 named files

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
btw @mbiarnes some of your changes are done with mine PR https://github.com/kiegroup/jbpm/pull/1696

**Comment by mbiarnes** [comment]
@mareknovotny OK - removed the files from this PR

**Pull request merged**
