### PR TITLE
(GSS) [7.11.1] [RHPAM-3584] Add task description

### PR DESCRIPTION
**Pull request by ruromero**
Signed-off-by: ruromero <rromerom@redhat.com>

**JIRA**: 

[https://issues.redhat.com/browse/RHPAM-3584](https://issues.redhat.com/browse/RHPAM-3584)

**referenced Pull Requests**: 

* https://github.com/kiegroup/jbpm/pull/1903 (cherry-pick)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by elguardian** [comment]
Jenkins retest this

**Comment by elguardian** [comment]
Jenkins retest this

**Comment by elguardian** [comment]
Jenkins retest this

**Comment by lazarotti** [comment]
Jenkins retest this

**Comment by lazarotti** [comment]
@ruromero jenkins is failing at 
org.jbpm.kie.services.test.AdvanceRuntimeDataServiceImplTest.testQueryHistoryAllNull[Pagination 0]
org.jbpm.kie.services.test.AdvanceRuntimeDataServiceImplTest.testQueryHistoryAllNull[Pagination 2] 

> java.lang.ClassCastException: java.sql.Timestamp cannot be cast to java.lang.String
> 	at org.jbpm.kie.services.impl.AbstractAdvanceRuntimeDataServiceImpl.toHistoryUserTaskInstanceWithPotOwnerDesc(AbstractAdvanceRuntimeDataServiceImpl.java:452)
> 	at org.jbpm.kie.services.impl.AbstractAdvanceRuntimeDataServiceImpl.collectUserTaskData(AbstractAdvanceRuntimeDataServiceImpl.java:393)
> 	at org.jbpm.kie.services.impl.AbstractAdvanceRuntimeDataServiceImpl.collectHistoryUserTaskData(AbstractAdvanceRuntimeDataServiceImpl.java:375)
> 	at org.jbpm.kie.services.impl.AbstractAdvanceRuntimeDataServiceImpl.queryProcessUserTasksByVariables(AbstractAdvanceRuntimeDataServiceImpl.java:258)
> 	at org.jbpm.kie.services.impl.AbstractAdvanceRuntimeDataServiceImpl.queryUserTasksByVariables(AbstractAdvanceRuntimeDataServiceImpl.java:123)
> 	at org.jbpm.kie.services.impl.AdvanceRuntimeDataServiceImpl.queryUserTasksByVariables(AdvanceRuntimeDataServiceImpl.java:68)
> 	at org.jbpm.kie.services.test.AdvanceRuntimeDataServiceImplTest.testQueryHistoryAllNull(AdvanceRuntimeDataServiceImplTest.java:502)

Don't you change the tests on master? Is there anything missing to be backported?

**Comment by ruromero** [comment]
Yes, it was missing the last commit after the pair review. It should be fine now

**Comment by ruromero** [comment]
It's now green @lazarotti

**Pull request merged**
