### PR TITLE
[JBPM-9818] - Fix in DDL scripts errors after adding end_date

### PR DESCRIPTION
**Pull request by afalhambra**
**[JBPM-9818](https://issues.redhat.com/browse/JBPM-9818)**: Fix in DDL scripts errors after adding end_date

### CODE REVIEW

**Comment by afalhambra** [comment]
Jenkins retest this

**Comment by afalhambra** [comment]
failure test not related
Jenkins retest this

**Comment by afalhambra** [comment]
Jenkins retest this

**Review by MarianMacik — APPROVED** [review]
Looks good to me. Nice job!

**Pull request merged**
