### PR TITLE
Add tests for 'async' as a default option for all tasks

### PR DESCRIPTION
**Pull request by mswiderski**
@MarianMacik see the second commit here to find out the adjustment of the test to work with signal. In general it was singling to early - before the async managed to trigger the signal node.

### CODE REVIEW

**Comment by MarianMacik** [comment]
+1

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
The fixed test failed previously on assert, because there were only 2 completed executor requests found. But on my machine it works as it should, i.e. there should be 3 completed commands (for intermediate catch event, script task and end node).

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Pull request merged**
