### PR TITLE
[6.5.x] RHBPMS-4854 - GlobalTimerService.timerJobsPerSession grows without bo…

### PR DESCRIPTION
**Pull request by mswiderski**
…unds

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
@tsurdilo do you mind trying this failing test locally? I can't reproduce it...

**Comment by tsurdilo** [comment]
@mswiderski I checkout out your local repo and in both command line and in-ide debugging/running the test passes. It's execution tho throws a ton of exceptions tho and I wonder if those in jenkins env causes timeout=30000 to exceed?

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by krisv** [comment]
Is there a product JIRA requesting this to be backported to 6.5.x already?  Please make sure to have this (with the acks) before backporting this to 6.5.x.

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
@krisv this PR is mainly to test the fix and let team on site to give it a go. It will wait till patch release jira is ready and ack'ed

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Pull request merged**
