### PR TITLE
7.11.x

### PR DESCRIPTION
**Pull request by 360CodeSafe**
Hi,
This is Qihoo360 CodeSafe Team, we found a Improper Restriction of XML External Entity Reference(XXE).Details are as follows:
default
At line 81,When DocumentBuilder is created, XML External Entity should be disabled.
Cheers
Qihoo360 CodeSafe Team

### CODE REVIEW

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser3** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser3** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by mswiderski** [comment]
closing as this is in conflict with current state of master, feel free to open jira and submit new PR

**Pull request closed without merging**
