### PR TITLE
[JBPM-9743] Fixing leak on TestEventEmitter

### PR DESCRIPTION
**Pull request by fjtirado**

### CODE REVIEW

**Comment by sutaakar** [comment]
@fjtirado Can you please rebase?

**Comment by fjtirado** [comment]
jenkins run fdb

**Comment by fjtirado** [comment]
jenkins run fdb

**Review by elguardian — APPROVED** [review]
LGTM

**Comment by mbiarnes** [comment]
Jenkins retest this

**Review by gmunozfe — APPROVED** [review]
Looks good to me, great work @fjtirado !

**Pull request merged**
