### PR TITLE
[DROOLS-6493] put kie conf files in different folders

### PR DESCRIPTION
**Pull request by mariofusco**
JIRA: https://issues.redhat.com/browse/DROOLS-6493

Related PRs:
droolsjbpm-knowledge: https://github.com/kiegroup/droolsjbpm-knowledge/pull/535
drools: https://github.com/kiegroup/drools/pull/3741
jbpm: https://github.com/kiegroup/jbpm/pull/1979
droolsjbpm-integration: https://github.com/kiegroup/droolsjbpm-integration/pull/2545
kie-jpmml-integration: https://github.com/kiegroup/kie-jpmml-integration/pull/60

### CODE REVIEW

**Comment by lucamolteni** [comment]
@mariofusco weren't these useless? In that case I'd rather delete those

**Comment by mariofusco** [comment]
> @mariofusco weren't these useless? In that case I'd rather delete those

I have no idea, I didn't check in detail. It seems to me that I haven't seen any failure in the fdb related to them, but I'm not 100% sure. Another thing that rings a bell is the fact that I haven't seen any of them listed in the static wiring of Kogito. Anyway for now I'd prefer to simply keep the current situation without changing much.

**Comment by mariofusco** [comment]
jenkins retest this

**Comment by mariofusco** [comment]
The 2 failing tests are caused by timeouts not related with this change.

**Review by danielezonca — APPROVED** [review]

**Comment by mariofusco** [comment]
jenkins retest this

**Pull request merged**
