### PR TITLE
Fix jbpm-remote-ejb-test

### PR DESCRIPTION
**Pull request by MarianMacik**
Hi, @mswiderski,

I have made some refinements to Remote EJB tests to support various DBs.

Thanks,

Marian

### CODE REVIEW

**Comment by MarianMacik** [comment]
Jenkins retest this

**Comment by MarianMacik** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Pull request merged**
