### PR TITLE
Index changes to address deadlocks on MySQL based on support feedback…

### PR DESCRIPTION
**Pull request by martinweiler**
… (KBase #3063771)

### CODE REVIEW

**Comment by MarianMacik** [comment]
Looks good to me, but are we ware of losing a bit of referential integrity since we are deleting one foreign key? Moreover, I see @sutaakar has this JIRA tested in the past, so probably he is a better contact to review.

**Comment by sutaakar** [comment]
Ok for me apart from point brought by Marian. Not sure what consequences it may bring.

**Comment by mswiderski** [comment]
I'd say it bring more good than potential issues so I opt at merging as it was already verified by several users, @MarianMacik @sutaakar any objections?

**Comment by sutaakar** [comment]
@mswiderski Fine for me

**Pull request merged**
