### PR TITLE
Fix tests compilation

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by mswiderski** [comment]
Was there any change in drools that broke it?

**Comment by cristianonicolai** [comment]
@mswiderski seems like this change https://github.com/kiegroup/drools/commit/72c72f5dd9be9c58d8257f05ee14d0850cdf28f5#diff-0e503b865a112436c2150fe4efeee70eL1862

**Comment by mswiderski** [comment]
Thanks, feel free to merge once it's green

**Pull request merged**
