### PR TITLE
JBPM-7346 Remove SNAPSHOT versions from tests where possible

### PR DESCRIPTION
**Pull request by baldimir**
JIRA: https://issues.jboss.org/browse/JBPM-7346

@mswiderski @MarianMacik could you please review?

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by baldimir** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by baldimir** [comment]
I will check this failure: https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbpm-pullrequests/1829/testReport/junit/org.jbpm.kie.services.test/FilteredKModuleDeploymentServiceTest/testMultipleRemotableInPojoJar/

Other seem unrelated.

**Comment by baldimir** [comment]
jenkins retest this

**Comment by baldimir** [comment]
jenkins retests this

**Pull request merged**
