### PR TITLE
[JBPM-9699] Register WorkItemHandler when kafka extension is enabled

### PR DESCRIPTION
**Pull request by fjtirado**
Do not assume message is a string in default handler

**JIRA**: 

[link](https://issues.redhat.com/browse/JBPM-9699)

**referenced Pull Requests**: 
kiegroup/droolsjbpm-integration#2455
https://github.com/kiegroup/droolsjbpm-knowledge/pull/515

### CODE REVIEW

**Review by gmunozfe — APPROVED** [review]
Looks good to me, well done @fjtirado !

**Comment by fjtirado** [comment]
jenkins retest this

**Comment by fjtirado** [comment]
jenkins retest this

**Review by elguardian — APPROVED** [review]

**Review by gmunozfe — CHANGES_REQUESTED** [review]
Need to delete moved test class: DeploymentDescriptorMergerTest.
I think DeploymentDescriptorManagerTest should be also moved

**Pull request merged**
