### PR TITLE
BXMSPROD-494 allow GA build on windows machine

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-494

related to

https://github.com/kiegroup/lienzo-core/pull/133
https://github.com/kiegroup/lienzo-tests/pull/108
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1471
https://github.com/kiegroup/kie-soup/pull/158
https://github.com/kiegroup/appformer/pull/1054
https://github.com/kiegroup/droolsjbpm-knowledge/pull/465
https://github.com/kiegroup/drools/pull/3116
https://github.com/kiegroup/optaplanner/pull/940
https://github.com/kiegroup/jbpm/pull/1758
https://github.com/kiegroup/kie-jpmml-integration/pull/43
https://github.com/kiegroup/droolsjbpm-integration/pull/2243
https://github.com/kiegroup/openshift-drools-hacep/pull/100
https://github.com/kiegroup/droolsjbpm-tools/pull/118
https://github.com/kiegroup/kie-uberfire-extensions/pull/106
https://github.com/kiegroup/kie-wb-playground/pull/97
https://github.com/kiegroup/kie-wb-common/pull/3423
https://github.com/kiegroup/drools-wb/pull/1423
https://github.com/kiegroup/optaplanner-wb/pull/381
https://github.com/kiegroup/jbpm-designer/pull/891
https://github.com/kiegroup/jbpm-wb/pull/1461
https://github.com/kiegroup/jbpm-work-items/pull/153
https://github.com/kiegroup/kie-docs/pull/2849
https://github.com/kiegroup/optaweb-employee-rostering/pull/498
https://github.com/kiegroup/optaweb-vehicle-routing/pull/367
https://github.com/kiegroup/kie-wb-distributions/pull/1062

### CODE REVIEW

**Comment by mareknovotny** [comment]
we need to rebase this @Ginxo

**Comment by Ginxo** [comment]
windows error `fatal: cannot create directory at 'kie-pmml-trusty/kie-pmml-models-drools-archetype/src/test/resources-filtered/projects/generated-naivebayes/reference/kie-pmml-models-naivebayes-compiler/src/main/java/org/kie/pmml/models/naive_bayes/compiler/factories': Filename too long`

**Comment by mareknovotny** [comment]
@Ginxo here the Github Actions for Windows and java 11 https://github.com/kiegroup/jbpm/pull/1758/checks?check_run_id=2085397839 is in weird status as it shows it failed but in the build log it says SUCCESS.

**Comment by Ginxo** [comment]
@mareknovotny it's due to https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/fd6da49cbe9bc500de080b61594ec26048f1384f/.ci/pull-request-config.yaml#L32
We have two options here, either to remove the `archive-artifacts` for jbpm or to upgrade build-chain-tool to deal with different configurations based on OS (ENV variables at the end)
I would go for the second one, wdyt?

**Comment by mareknovotny** [comment]
do we want to update this or close it? @Ginxo

**Comment by Ginxo** [comment]
> do we want to update this or close it? @Ginxo

see https://github.com/kiegroup/jbpm-work-items/pull/153#issuecomment-1010842039

**Comment by mareknovotny** [comment]
we can close this as windows build is here blocked by Gwt maven plugin

**Pull request closed without merging**
