### PR TITLE
JBPM-5842: Add more LoadBalanceStrategy test coverage

### PR DESCRIPTION
**Pull request by domhanak**
Extends test of current LoadBalanceAssignmentStrategy
Fixes a bug where users in excluded groups wouldn't appear in excluded user list and ended up still being assigned.

### CODE REVIEW

**Comment by domhanak** [comment]
jenkins retest this

**Comment by domhanak** [comment]
Failures seems unrelated.

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by domhanak** [comment]
@lanceleverich I would leave the name as it is, since these tests are mainly focused on unti-testing LoadBalanceAssignmenStrategy not how the calculator counts the load, that should be in unit-test of that calculator.

**Pull request merged**
