### PR TITLE
[JBPM-9452] ClassCastException fix

### PR DESCRIPTION
**Pull request by hmatt1**
ClassCastException occurs when mapping DMN output to a Java Object in a BPMN

**Thank you for submitting this pull request**

**JIRA**: 

[JBPM-9452](https://issues.redhat.com/browse/JBPM-9452)

I created a minimal, reproducible example [here](https://github.com/Optum/kie-examples/tree/master/1) and verified this fixes the issue. I didn't see any unit tests for the `RuleSetNodeInstance` class so I wasn't sure what would be the best way to get an automated test in place for this. If you think we need one, I'd be happy to work on that and I'd appreciate some guidance to point me in the right direction.

**referenced Pull Requests**:

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by bxf12315** [comment]
Jenkins retest this

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins retest this

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by hmatt1** [comment]
@bxf12315 @vmiklos @atoulme do you know what's going on with the build?

**Comment by vmiklos** [comment]
Sorry, no idea. I haven't contributed to this project in the recent past :-)

**Comment by hmatt1** [comment]
@elguardian do you know what's going on with the build?

**Comment by bxf12315** [comment]
Jenkins retest this

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by hmatt1** [comment]
Jenkins retest this

**Comment by hmatt1** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by hmatt1** [comment]
Not sure how to debug this failure, can anyone help? Is it failing because of these changes?

**Comment by bxf12315** [comment]
> Not sure how to debug this failure, can anyone help? Is it failing because of these changes?

You need to ask the gatekeep to review your PR.

**Comment by bxf12315** [comment]
Jenkins retest this

**Review by mariofusco — APPROVED** [review]

**Comment by hmatt1** [comment]
Thanks to Mario for the review :smile:

Can someone help get this build to pass please? Hoping we can get this merged soon since it has been approved.

**Comment by hmatt1** [comment]
Can someone help get this build to pass please? Hoping we can get this merged soon since it has been approved.

**Comment by hmatt1** [comment]
Can someone help get this build to pass please? I can't see the failures from the downstream builds

**Comment by hmatt1** [comment]
@elguardian are you able to help with this one? Not sure how to take this forward

**Comment by elguardian** [comment]
this is very close to this problem

https://github.com/kiegroup/jbpm/pull/1947

I am merging.

**Comment by elguardian** [comment]
thx for the contribution @hmatt1  !

**Pull request merged**
