### PR TITLE
JBPM-7661: NodeInstanceLog for node left events should be fired on be…

### PR DESCRIPTION
**Pull request by nmirasch**
…foreNodeLeft

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@nmirasch yeah, tricky one... I'm wondering if we should be more strict and assert each NodeInstanceLog and the order they are returned/created.  Maybe adding that to _testLogger1_ method would be reasonable.

**Comment by nmirasch** [comment]
@cristianonicolai added that sample log sorting test.

**Comment by cristianonicolai** [comment]
looks good to me, just retrying tests to get a green build

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by nmirasch** [comment]
Jenkins retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
@mswiderski build keeps failing on _org.jbpm.test.container.test.ejbservices.tx.ETransactionTest_ tests, doesnt seem related to me, not sure if you can take a quick look on that.

**Comment by mswiderski** [comment]
@MarianMacik is looking into it and we should get update soon

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by nmirasch** [comment]
@MarianMacik I tried to fix the integration test related in https://github.com/kiegroup/droolsjbpm-integration/pull/1582 I change the expected values sorting according with this ,Could you take a look? Thanks!

**Pull request merged**
