### PR TITLE
[JBPM-8688] Timers do not recover after database disconnection (#1520)

### PR DESCRIPTION
**Pull request by elguardian**
providing recovery of timers. executed till it is succeed

### CODE REVIEW

**Comment by elguardian** [comment]
backport #1520

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
Jenkins retest this

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
jenkins retest this

**Pull request merged**
