### PR TITLE
[JBPM-9638] - Test case for JBPM-9623 (Dynamic Sub process is getting invoked twice instead of once when implemented in loop back)

### PR DESCRIPTION
**Pull request by afalhambra**
**[JBPM-9638](https://issues.redhat.com/browse/JBPM-9638)**: Test case for JBPM-9623 (Dynamic Sub process is getting invoked twice instead of once when implemented in loop back).

### CODE REVIEW

**Comment by afalhambra** [comment]
Jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by afalhambra** [comment]
CI timing out. Retriggering again
Jenkins retest this

**Comment by afalhambra** [comment]
@mareknovotny @elguardian could you please merge?

**Review by gmunozfe — APPROVED** [review]
Looks good to me, nice job @afalhambra !

**Pull request merged**
