### PR TITLE
Fix large jbpm-container archives

### PR DESCRIPTION
**Pull request by MarianMacik**
@mswiderski @psiroky here is the change we spoke about. Maybe it would help.

### CODE REVIEW

**Comment by MarianMacik** [comment]
Build no. 1 successful

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
Build no. 2 successful

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by MarianMacik** [comment]
I agree with merging this.

**Pull request merged**
