### PR TITLE
[JBPM-9623] Dynamic Sub process is getting invoked twice instead of once when implemented in loop back.

### PR DESCRIPTION
**Pull request by elguardian**
Jira: https://issues.redhat.com/browse/JBPM-9623

### CODE REVIEW

**Review by afalhambra — CHANGES_REQUESTED** [review]
Please remove below file from the PR

https://github.com/kiegroup/jbpm/blob/5c26fbdcac1b9dcadb4434618ab380f7cba7770d/jbpm-case-mgmt/jbpm-case-mgmt-impl/ObjectStore/ShadowNoFileLockStore/defaultStore/Recovery/TransactionStatusManager/0_ffff7f000001_85c9_6013ced0_a

Also, would you please add a test case for this scenario?

**Comment by elguardian** [comment]
Jenkins retest this please.

**Comment by elguardian** [comment]
Jenkins retest this

**Comment by elguardian** [comment]
Jenkins retest this

**Pull request merged**
