### PR TITLE
JBPM-6208 - Case file for related documents: backend - jBPM engine te…

### PR DESCRIPTION
**Pull request by MarianMacik**
…st development

Added additional coverage for the following test methods:
* addDataToCaseFile with Map parameter
* removeDataFromCaseFile with multiple items
* newCaseFileInstance methods for non-existing case definition
* getCaseFileInstance for not existing case instance

### CODE REVIEW

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Pull request merged**
