### PR TITLE
JBPM-4646 - case management - case file data audit trail

### PR DESCRIPTION
**Pull request by mswiderski**
@tsurdilo do you mind taking a look?

it still requires update to DDL scripts that I'll be working on soon.

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by tsurdilo** [comment]
@mswiderski - really cool!

**Comment by tsurdilo** [comment]
jenkins please retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Pull request merged**
