### PR TITLE
RHPAM-806: Enrich Task event listeners data

### PR DESCRIPTION
**Pull request by mcivantos-tribalyte**
@mswiderski This is the PR to 7.7.x related to https://github.com/kiegroup/jbpm/pull/1184

### CODE REVIEW

**Comment by mswiderski** [comment]
ok to test

**Comment by MarianMacik** [comment]
@mcivantos-tribalyte Thanks!

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Pull request merged**
