### PR TITLE
[JBPM-9798] Accept all possible properties for Kafka Consumer/Producer

### PR DESCRIPTION
**Pull request by fjtirado**
Adding functionality for Kafka event emitter

**JIRA**: 

[link](https://issues.redhat.com/browse/JBPM-9798)

### CODE REVIEW

**Comment by fjtirado** [comment]
jenkins retest this

**Review by elguardian — APPROVED** [review]
LGTM

**Review by gmunozfe — APPROVED** [review]
Looks good to me, stupendous work @fjtirado !
You can even add the properties for ScramLoginModule but up to you, I've checked that works like a charm

**Comment by fjtirado** [comment]
jenkins retest this

**Pull request merged**
