### PR TITLE
JBPM-5851 - Technical Error Events - enhanced DB filter to include ro…

### PR DESCRIPTION
**Pull request by mswiderski**
…llback exception as well that is used when running on Oracle and Postgres

@MarianMacik here is a fix for the test we talked about on Oracle and Postgres. I verified it on Postgres but didn't check it on Oracle, do you mid double check it?

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by MarianMacik** [comment]
@mswiderski it works with Oracle 12c too, so I think it is fixed now. Once you merge this I will run the whole test suite to be 100% sure.

Thanks!

**Comment by mswiderski** [comment]
@MarianMacik thanks for checking this. merged so it's ready for full test run

**Pull request merged**
