### PR TITLE
RHBPMS-4801 - InMemorySessionFactory has apparent memory leak - fixed…

### PR DESCRIPTION
**Pull request by mswiderski**
… OSGi imported packaged

@mbiarnes @hasys here is the fix for failing test org.kie.karaf.itest.KieSpringjBPMPersistenceKarafIntegrationTest.testJbpmRuntimeManager

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by mswiderski** [comment]
all failed tests are related to kie wb REST tests

**Comment by mswiderski** [comment]
Jenkins execute full downstream build

**Comment by mswiderski** [comment]
Jenkins execute full downstream build

**Pull request merged**
