### PR TITLE
JBPM-9044 - Upgrade kiegroup repos to Wildfly 18.0.1.Final

### PR DESCRIPTION
**Pull request by MarianMacik**
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1209

### CODE REVIEW

**Comment by MarianMacik** [comment]
@mareknovotny I will try it here and if it works, I will push it to your PR.

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
replaced by #1601

**Pull request closed without merging**
