### PR TITLE
increase test timeout for AsyncContinuationSupportTest:testAsyncModeW…

### PR DESCRIPTION
**Pull request by tsurdilo**
…ithParallelGateway

added formatting updates as well. change to test timeout -- https://github.com/kiegroup/jbpm/compare/master...tsurdilo:executor-test-fix?expand=1#diff-468a09dd3778c6a0a5c929577008992eR1013

### CODE REVIEW

**Comment by tsurdilo** [comment]
@mswiderski sure ill remove those -- will do another pr

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by MarianMacik** [comment]
Guys, the real issue is this one: https://issues.jboss.org/browse/JBPM-8644 Increasing of the timeout won't help. Bear in mind that apparently this doesn't happen on 7.18.x branch.

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by mareknovotny** [comment]
if there is a real problem we should close this PR and work on https://issues.jboss.org/browse/JBPM-8644.

WDYT? @tsurdilo, @MarianMacik, @elguardian

**Comment by tsurdilo** [comment]
closing this one, will work on https://issues.jboss.org/browse/JBPM-8644

**Pull request closed without merging**
