### PR TITLE
[7.59.x][JBPM-9878] Missing jakarta dependency for jdk11 workitems-bpmn2 tests

### PR DESCRIPTION
**Pull request by gmunozfe**
**JIRA**: [JBPM-9878](https://issues.redhat.com/browse/JBPM-9878)

Backport from 1e672680de770a5e766f8e97f9dfdeea68a649e5

### CODE REVIEW

**Review by afalhambra — APPROVED** [review]
looks good to me, great work @gmunozfe

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by gmunozfe** [comment]
@mareknovotny this is ready to merge

**Pull request merged**
