### PR TITLE
JBPM-9099 Make db columns validation optional in SQLDataSet

### PR DESCRIPTION
**Pull request by cristianonicolai**
**JIRA**:

[JBPM-9099](https://issues.redhat.com/browse/JBPM-9099)

**referenced Pull Requests**: 

* https://github.com/kiegroup/kie-soup/pull/169

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Jenkins run fdb

**Comment by fjtirado** [comment]
Lets keep this one as backup of https://github.com/kiegroup/kie-soup/pull/168, which should achieve the same goal

**Comment by cristianonicolai** [comment]
Jenkins run fdb

**Comment by cristianonicolai** [comment]
Jenkins run fdb

**Comment by cristianonicolai** [comment]
Jenkins run fdb

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
Jenkins run fdb

**Comment by elguardian** [comment]
this was superseeded already with query opt and limit = 0

**Pull request closed without merging**
