### PR TITLE
JBPM-8085 - RESTWorkItemHandler PATCH operation support

### PR DESCRIPTION
**Pull request by SimonRinguette**
We have updated the RESTWorkItemHandler to support the PATCH HTTP verb

### CODE REVIEW

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by SimonRinguette** [comment]
@tsurdilo for the unit test, the @PATCH annotations for JAX-RS was introduced in 2.1. The current dependency is on 2.0.1 so it's not really easy to add a test for it.

Suggestions?

**Comment by SimonRinguette** [comment]
I could add the Patch Annotation locally using the suggestion found here if this is something you would consider: https://stackoverflow.com/questions/17897171/how-to-have-a-patch-annotation-for-jax-rs

**Comment by tsurdilo** [comment]
@SimonRinguette I'm OK with the workaround you found. Maybe add the annotation to https://github.com/kiegroup/jbpm/tree/master/jbpm-workitems/jbpm-workitems-rest/src/test/java/org/jbpm/process/workitem/rest with a comment to remove it once jax-rs depends is updated. 
@mswiderski wdyt?

**Comment by mswiderski** [comment]
created jira for this work 
https://issues.jboss.org/browse/JBPM-8085, @SimonRinguette would you mind to update commit message?

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by SimonRinguette** [comment]
@mswiderski Updated!

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
test failure in jenkins not related to these changes (its the org.jbpm.executor.DBUnavilabilityExecutorTest.reoccurringExecutionTest again)

**Comment by mswiderski** [comment]
@tsurdilo I will go over this failing test to make it stable

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins retest please

**Pull request merged**
