### PR TITLE
[BAQE-1534] Update all test cases across jbpm regarding persistence for DB Jenkins matrix job

### PR DESCRIPTION
**Pull request by afalhambra**
**[BAQE-1534](https://issues.redhat.com/browse/BAQE-1534)**: Update all test cases across jbpm regarding persistence for DB Jenkins matrix job

### CODE REVIEW

**Comment by afalhambra** [comment]
Jenkins do fdb

**Review by MarianMacik — APPROVED** [review]
Looks good. I don't remember now if you tested it already on the full DB matrix, but in case you didn't I think it would be good to check it.

**Comment by afalhambra** [comment]
> Looks good. I don't remember now if you tested it already on the full DB matrix, but in case you didn't I think it would be good to check it.
> 

Thanks a lot Marian for the review. I did already, but I will do it again, after rebasing the PR, just to double check and let you know.

**Comment by afalhambra** [comment]
Jenkins do fdb

**Comment by afalhambra** [comment]
@MarianMacik - have a look at the DB matrix jenkins job, if you want. I just launched again with this PR and works fine.

https://*********/job/custom/job/antferna/job/custom-community-tests-jbpm-db-matrix/174/

**Comment by afalhambra** [comment]
Jenkins run fdb

**Comment by afalhambra** [comment]
Jenkins run fdb

**Comment by afalhambra** [comment]
Jenkins run fdb

**Comment by afalhambra** [comment]
Jenkins run fdb

**Comment by afalhambra** [comment]
Jenkins run fdb

**Comment by afalhambra** [comment]
Jenkins run fdb

**Comment by afalhambra** [comment]
Jenkins run fdb

**Comment by afalhambra** [comment]
@MarianMacik can you please merge? CI failed tests are not related to this PR

**Comment by mareknovotny** [comment]
who will fix the failures? Please report the issues for failures and try to find responsible person who will fix them ASAP

**Comment by afalhambra** [comment]
Jenkins retest this

**Comment by afalhambra** [comment]
Jenkins run fdb

**Pull request merged**
