### PR TITLE
JBPM-5855 Added last modification date to task audit info

### PR DESCRIPTION
**Pull request by rbarriuso**
Fixed indentation format in `JPATaskLifeCycleEventListener.java` (besides adding calls to `updateLastModifiedDate()`)

### CODE REVIEW

**Comment by cristianonicolai** [comment]
ok to test

**Comment by cristianonicolai** [comment]
@rbarriuso overall looks good to me but I'll let @mswiderski do a final review. Regarding the code style formatting on `JPATaskLifeCycleEventListener.java`, I still get quite a few changes if I try to format it using the latest conventions.

**Comment by mswiderski** [comment]
looks ok, just a lot of "noise changes" in the JPATaskLifeCycleEventListener class. Is this because of new formater?

**Comment by rbarriuso** [comment]
The indentation of that class had a mix of tabs and spaces, so I converted
all to spaces (4 per indentation level, as the style guide says).
Now it's easier to read, though I know it generated a lot of diff changes.

**Comment by rbarriuso** [comment]
Added missing bpms DB upgrade scripts

**Pull request merged**
