### PR TITLE
BXMSPROD-702 jbm-distribution removed from community-only profile

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-702

### CODE REVIEW

**Comment by Ginxo** [comment]
Jenkins execute full downstream production build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by Ginxo** [comment]
The prod build is fixed by this https://github.com/kiegroup/kie-wb-distributions/pull/1030 (which was merged after starting it), relaunching prod.

**Comment by Ginxo** [comment]
Jenkins execute full downstream production build

**Comment by Ginxo** [comment]
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/upstream-downstream/job/jbpm.downstream/4 OutOfMemoryError, relaunching.

**Comment by Ginxo** [comment]
Jenkins execute full downstream build

**Pull request merged**
