### PR TITLE
[DROOLS-6566] Add missing package import (required by org.jbpm.runtim…

### PR DESCRIPTION
**Pull request by grgrzybek**
…e.manager.impl.error.filters.TaskExecutionErrorFilter)

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
ok to test

**Comment by mbiarnes** [comment]
Jenkins retest this

**Review by jiripetrlik — APPROVED** [review]

**Comment by mareknovotny** [comment]
can this PR be merged without https://github.com/kiegroup/droolsjbpm-integration/pull/2591 ?

**Comment by grgrzybek** [comment]
> can this PR be merged without [kiegroup/droolsjbpm-integration#2591](https://github.com/kiegroup/droolsjbpm-integration/pull/2591) ?

Yes, it can. kiegroup/droolsjbpm-integration#2591 is the one that needs kiegroup/jbpm#2011, not the opposite ;)

**Pull request merged**
